-- Chunk 7 of 7 (431 schools)
INSERT INTO public.schools (name, town) VALUES
  ('The Sir Robert Woodard Academy', 'Sompting'),
  ('The Sittingbourne School', 'Sittingbourne'),
  ('The Skinners'' School', 'Tunbridge Wells'),
  ('The Skipton Academy', 'Skipton'),
  ('The Snaith School', 'Goole'),
  ('The South Wolds Academy & Sixth Form', 'Nottingham'),
  ('The Spires College', 'Torquay'),
  ('The St Lawrence Academy', 'Scunthorpe'),
  ('The St Leonards Academy', 'St Leonards-on-Sea'),
  ('The St Marylebone CofE School', 'London'),
  ('The St Thomas the Apostle College', 'London'),
  ('The Stanway School', 'Colchester'),
  ('The Steiner Academy Hereford', 'Hereford'),
  ('The Stockwood Park Academy', 'Luton'),
  ('The Stonehenge School', 'Amesbury'),
  ('The Stourport High School and Sixth Form College', 'Stourport-on-Severn'),
  ('The Streetly Academy', 'Sutton Coldfield'),
  ('The Studio School Liverpool', 'Liverpool'),
  ('The Suthers School', 'Newark'),
  ('The Sutton Academy', 'St Helens'),
  ('The Swan School', 'Oxford'),
  ('The Swanage School', 'Swanage'),
  ('The Sweyne Park School', 'Rayleigh'),
  ('The Sydney Russell School', 'Dagenham'),
  ('The Telford Langley School', 'Telford'),
  ('The Telford Park School', 'Telford'),
  ('The Thetford Academy', 'Thetford'),
  ('The Thomas Adams School', 'Shrewsbury'),
  ('The Thomas Alleyne Academy', 'Stevenage'),
  ('The Thomas Aveling School', 'Rochester'),
  ('The Thomas Hardye School', 'Dorchester'),
  ('The Thomas Lord Audley School', 'Colchester'),
  ('The Tiffin Girls'' School', 'Kingston upon Thames'),
  ('The Totteridge Academy', 'London'),
  ('The Toynbee School', 'Eastleigh'),
  ('The Trafalgar School at Downton', 'Salisbury'),
  ('The Trinity Catholic School A Voluntary Academy', 'Nottingham'),
  ('The Trinity School', 'Colchester'),
  ('The Turing School', 'Eastbourne'),
  ('The UCL Academy', 'Camden'),
  ('The University of Birmingham School', 'Birmingham'),
  ('The Ursuline Academy Ilford', 'Ilford'),
  ('The Urswick School - A Church of England Secondary School', 'London'),
  ('The Vale Academy', 'Brigg'),
  ('The Valley Leadership Academy', 'Bacup'),
  ('The Victory Academy', 'Chatham'),
  ('The Vyne Community School', 'Basingstoke'),
  ('The Warren School', 'Romford'),
  ('The Warriner School', 'Banbury'),
  ('The Wavell School', 'Farnborough'),
  ('The Wellington Academy', 'Ludgershall'),
  ('The Wells Academy', 'Nottingham'),
  ('The West Bridgford School', 'Nottingham'),
  ('The Westgate School', 'Winchester'),
  ('The Westgate School', 'Slough'),
  ('The Westleigh School', 'Leigh'),
  ('The Weston Road Academy', 'Stafford'),
  ('The Westwood Academy', 'Coventry'),
  ('The Whitby High School', 'Ellesmere Port'),
  ('The Whitehaven Academy', 'Whitehaven'),
  ('The Whitstable School', 'Whitstable'),
  ('The Willink School', 'Reading'),
  ('The Wilnecote School', 'Tamworth'),
  ('The Windsor Boys'' School', 'Windsor'),
  ('The Winsford Academy', 'Winsford'),
  ('The Winstanley School', 'Leicester'),
  ('The Winston Churchill School A Specialist Sports College', 'Woking'),
  ('The Wisbech Academy', 'Wisbech'),
  ('The Woodroffe School', 'Lyme Regis'),
  ('The Wordsley School', 'Stourbridge'),
  ('The WREN School', 'Reading'),
  ('Theale Green School', 'Reading'),
  ('Therfield School', 'Leatherhead'),
  ('Thirsk School & Sixth Form College', 'Thirsk'),
  ('Thistley Hough Academy', 'Stoke-on-Trent'),
  ('Thomas Alleyne''s High School', 'Uttoxeter'),
  ('Thomas Bennett Community College', 'Crawley'),
  ('Thomas Clarkson Academy', 'Wisbech'),
  ('Thomas Deacon Academy', 'Peterborough'),
  ('Thomas Estley Community College', 'Leicester'),
  ('Thomas Gainsborough School', 'Sudbury'),
  ('Thomas Hall School', 'Exeter'),
  ('Thomas Keble School', 'Stroud'),
  ('Thomas Knyvett College', 'Ashford'),
  ('Thomas Middlecott Academy', 'Boston'),
  ('Thomas Mills High School & Sixth Form', 'Woodbridge'),
  ('Thomas More Catholic School', 'Purley'),
  ('Thomas Tallis School', 'London'),
  ('Thomas Telford University Technical College', 'Wolverhampton'),
  ('Thornaby Academy', 'Stockton-on-Tees'),
  ('Thornden School', 'Eastleigh'),
  ('Thornhill Academy', 'Sunderland'),
  ('Thornhill Community Academy, A Share Academy', 'Dewsbury'),
  ('Thornleigh Salesian College', 'Bolton'),
  ('Thorns Collegiate Academy', 'Brierley Hill'),
  ('Thorp Academy', 'Ryton'),
  ('Thorpe St Andrew School and Sixth Form', 'Norwich'),
  ('Three Rivers Academy', 'Walton-on-Thames'),
  ('Thrybergh Academy', 'Rotherham'),
  ('Thurstable School', 'Colchester'),
  ('Thurston Community College', 'Bury St Edmunds'),
  ('Tibshelf Community School', 'Alfreton'),
  ('Tiffin School', 'Kingston upon Thames'),
  ('Tile Cross Academy', 'Birmingham'),
  ('Titus Salt School', 'Bradford'),
  ('Tiverton High School', 'Tiverton'),
  ('Todmorden High School, A SHARE Academy', 'Todmorden'),
  ('Tolworth Girls'' School and Sixth Form', 'Surbiton'),
  ('Tomlinscote School', 'Camberley'),
  ('Tonbridge Grammar School', 'Tonbridge'),
  ('Tong Leadership Academy', 'Bradford'),
  ('Toot Hill School', 'Nottingham'),
  ('Tor Bridge High', 'Plymouth'),
  ('Torpoint Community College', 'Torpoint'),
  ('Torquay Academy', 'Torquay'),
  ('Torquay Boys'' Grammar School', 'Torquay'),
  ('Torquay Girls'' Grammar School', 'Torquay'),
  ('Tottington High School', 'Bury'),
  ('Towers School and Sixth Form Centre', 'Ashford'),
  ('Townley Grammar School', 'Bexleyheath'),
  ('Townsend Church of England School', 'St Albans'),
  ('Trafalgar School', 'Portsmouth'),
  ('Trentham Academy', 'Stoke-on-Trent'),
  ('Trevelyan Middle School', 'Windsor'),
  ('Treviglas Academy', 'Newquay'),
  ('Tring School', 'Tring'),
  ('Trinity Academy', 'Doncaster'),
  ('Trinity Academy', 'London'),
  ('Trinity Academy', 'Bristol'),
  ('Trinity Academy Bradford', 'Bradford'),
  ('Trinity Academy Cathedral', 'Wakefield'),
  ('Trinity Academy Grammar', 'Sowerby Bridge'),
  ('Trinity Academy Halifax', 'Halifax'),
  ('Trinity Academy Leeds', 'Leeds'),
  ('Trinity Academy St. Edwards', 'Barnsley'),
  ('Trinity Catholic College', 'Middlesbrough'),
  ('Trinity Catholic High School', 'Woodford Green'),
  ('Trinity Catholic School', 'Leamington Spa'),
  ('Trinity Church of England School, Belvedere', 'Belvedere'),
  ('Trinity Church of England School, Lewisham', 'London'),
  ('Trinity CofE High School', 'Manchester'),
  ('Trinity High School and Sixth Form Centre', 'Redditch'),
  ('Trinity School', 'Carlisle'),
  ('Trinity School', 'Newbury'),
  ('Trinity School', 'Sevenoaks'),
  ('Trumpington Community College', 'Cambridge'),
  ('Tudor Grange Academy Kingshurst', 'Birmingham'),
  ('Tudor Grange Academy Redditch', 'Redditch'),
  ('Tudor Grange Academy Worcester', 'Worcester'),
  ('Tudor Grange Academy, Solihull', 'Solihull'),
  ('Tudor Grange Samworth Academy, A church of England School', 'Leicester'),
  ('Tunbridge Wells Girls'' Grammar School', 'Tunbridge Wells'),
  ('Tunbridge Wells Grammar School for Boys', 'Tunbridge Wells'),
  ('Tupton Hall School', 'Chesterfield'),
  ('Turing House School', 'Twickenham'),
  ('Turner Free School', 'Folkestone'),
  ('Turton School', 'Bolton'),
  ('Turves Green Boys'' School', 'Birmingham'),
  ('Tute Education Ltd', 'Chester'),
  ('Tuxford Academy', 'Newark'),
  ('Tweedmouth Community Middle School', 'Berwick-upon-Tweed'),
  ('Twickenham School', 'Twickenham'),
  ('Twyford Church of England High School', 'London'),
  ('Twynham School', 'Christchurch'),
  ('Tytherington School', 'Macclesfield'),
  ('Uckfield College', 'Uckfield'),
  ('Uffculme School', 'Cullompton'),
  ('Ullswater Community College', 'Penrith'),
  ('Ulverston Victoria High School', 'Ulverston'),
  ('Unity Academy Blackpool', 'Blackpool'),
  ('Unity College', 'Burnley'),
  ('University Academy Holbeach', 'Spalding'),
  ('University Academy Long Sutton', 'Spalding'),
  ('University Collegiate School', 'Bolton'),
  ('University Technical College Leeds', 'Leeds'),
  ('University Technical College Norfolk', 'Norwich'),
  ('Unsworth Academy', 'Bury'),
  ('Up Holland High School', 'Wigan'),
  ('Uplands Academy', 'Wadhurst'),
  ('Upper Batley High School', 'Batley'),
  ('Upper Shirley High School', 'Southampton'),
  ('Upper Wharfedale School', 'Skipton'),
  ('Uppingham Community College', 'Uppingham'),
  ('Upton Court Grammar School', 'Slough'),
  ('Upton Hall School FCJ', 'Wirral'),
  ('Upton-by-Chester High School', 'Chester'),
  ('Urmston Grammar Academy', 'Manchester'),
  ('Ursuline College', 'Westgate-on-Sea'),
  ('Ursuline High School Wimbledon', 'London'),
  ('UTC Derby Pride Park', 'Derby'),
  ('UTC Heathrow', 'Northwood'),
  ('UTC Oxfordshire', 'Didcot'),
  ('UTC Plymouth', 'Plymouth'),
  ('UTC Portsmouth', 'Portsmouth'),
  ('UTC Reading', 'Reading'),
  ('UTC Sheffield City Centre', 'Sheffield'),
  ('UTC Sheffield Olympic Legacy Park', 'Sheffield'),
  ('UTC South Durham', 'Newton Aycliffe'),
  ('UTC Swindon', 'Swindon'),
  ('UTC Warrington', 'Warrington'),
  ('Uxbridge High School', 'Uxbridge'),
  ('Vale of York Academy', 'York'),
  ('Valentines High School', 'Ilford'),
  ('Valley Academy', 'Bradford'),
  ('Valley Gardens Middle School', 'Whitley Bay'),
  ('Valley Park School', 'Maidstone'),
  ('Vandyke Upper School', 'Leighton Buzzard'),
  ('Varndean School', 'Brighton'),
  ('Venerable Bede Church of England Academy', 'Sunderland'),
  ('Verulam School', 'St Albans'),
  ('Villiers High School', 'Southall'),
  ('Vista Academy Littleport', 'Ely'),
  ('Vyners School', 'Uxbridge'),
  ('Waddesdon Church of England School', 'Aylesbury'),
  ('Wade Deacon High School', 'Widnes'),
  ('Wadebridge School', 'Wadebridge'),
  ('Wadham School', 'Crewkerne'),
  ('Waingels', 'Reading'),
  ('Walbottle Academy', 'Newcastle-upon-Tyne'),
  ('Waldegrave School', 'Twickenham'),
  ('Walderslade School', 'Chatham'),
  ('Wales High School', 'Sheffield'),
  ('Walker Riverside Academy', 'Newcastle-upon-Tyne'),
  ('Walkwood Church of England Middle School', 'Redditch'),
  ('Wallingford School', 'Wallingford'),
  ('Wallington County Grammar School', 'Wallington'),
  ('Wallington High School for Girls', 'Wallington'),
  ('Walney School', 'Barrow-in-Furness'),
  ('Walsall Academy', 'Walsall'),
  ('Walsall Studio School', 'Walsall'),
  ('Waltham Toll Bar Academy', 'Grimsby'),
  ('Walthamstow Academy', 'London'),
  ('Walthamstow School for Girls', 'London'),
  ('Walton Academy', 'Grantham'),
  ('Walton High', 'Milton Keynes'),
  ('Walton High School', 'Stafford'),
  ('Walton Priory Middle School', 'Stone'),
  ('Walton-Le-Dale High School', 'Preston'),
  ('Wanstead High School', 'London'),
  ('Wapping High School', 'London'),
  ('Warblington School', 'Havant'),
  ('Warden Park Secondary Academy', 'Haywards Heath'),
  ('Wardle Academy', 'Rochdale'),
  ('Warlingham School', 'Warlingham'),
  ('Waseley Hills High School', 'Birmingham'),
  ('Washington Academy', 'Washington'),
  ('Washwood Heath Academy', 'Birmingham'),
  ('Waterfront UTC', 'Chatham'),
  ('Waterhead Academy', 'Oldham'),
  ('Waterside Academy', 'London'),
  ('Watford Grammar School for Boys', 'Watford'),
  ('Watford Grammar School for Girls', 'Watford'),
  ('Wath Academy', 'Rotherham'),
  ('Watling Academy', 'Milton Keynes'),
  ('Waverley School', 'Birmingham'),
  ('Waverley Studio College', 'Birmingham'),
  ('Wayland Academy', 'Thetford'),
  ('Weald of Kent Grammar School', 'Tonbridge'),
  ('Weald School, The', 'Billingshurst'),
  ('Weatherhead High School', 'Wallasey'),
  ('Weaverham High School', 'Northwich'),
  ('Weavers Academy', 'Wellingborough'),
  ('Wednesfield Academy', 'Wolverhampton'),
  ('Weldon Village Academy', 'Corby'),
  ('Wellacre Technology Academy', 'Manchester'),
  ('Welland Park Academy', 'Market Harborough'),
  ('Wellfield Academy', 'Leyland'),
  ('Wellfield Middle School', 'Whitley Bay'),
  ('Wellfield School', 'Wingate'),
  ('Welling School', 'Welling'),
  ('Wellington School', 'Altrincham'),
  ('Wellsway School', 'Bristol'),
  ('Wembley High Technology College', 'North Wembley'),
  ('Wensleydale School', 'Leyburn'),
  ('Weobley High School', 'Hereford'),
  ('Werneth School', 'Stockport'),
  ('West Bromwich Collegiate Academy', 'West Bromwich'),
  ('West Coventry Academy', 'Coventry'),
  ('West Craven High School', 'Barnoldswick'),
  ('West Derby School', 'Liverpool'),
  ('West Exe School', 'Exeter'),
  ('West Grantham Church of England Secondary Academy', 'Grantham'),
  ('West Hatch High School', 'Chigwell'),
  ('West Hill School', 'Stalybridge'),
  ('West Kirby Grammar School', 'Wirral'),
  ('West Lakes Academy', 'Egremont'),
  ('West London Free School', 'London'),
  ('West Moors Middle School', 'Ferndown'),
  ('West Park School', 'Derby'),
  ('West Somerset College', 'Minehead'),
  ('West Walsall E-ACT Academy', 'Walsall'),
  ('Westborough High School', 'Dewsbury'),
  ('Westbourne Academy', 'Ipswich'),
  ('Westcliff High School for Boys Academy', 'Westcliff-on-Sea'),
  ('Westcliff High School for Girls', 'Westcliff-on-Sea'),
  ('Westfield Academy', 'Yeovil'),
  ('Westfield Academy', 'Watford'),
  ('Westfield School', 'Sheffield'),
  ('Westhoughton High School', 'Bolton'),
  ('Westlands School', 'Sittingbourne'),
  ('Westminster Academy', 'London'),
  ('Westminster City School', 'London'),
  ('Weston Favell Academy', 'Northampton'),
  ('Weston Secondary School', 'Southampton'),
  ('Westwood College', 'Leek'),
  ('Wetherby High School', 'Wetherby'),
  ('Wexham School', 'Slough'),
  ('Wey Valley Academy', 'Weymouth'),
  ('Weydon School', 'Farnham'),
  ('Whalley Range 11-18 High School', 'Manchester'),
  ('Wheatley Park School', 'Oxford'),
  ('Wheelers Lane Technology College', 'Birmingham'),
  ('Whickham School', 'Newcastle-upon-Tyne'),
  ('Whitburn Church of England Academy', 'Sunderland'),
  ('Whitby School', 'Whitby'),
  ('Whitcliffe Mount, A Share Academy', 'Cleckheaton'),
  ('Whitecross Hereford', 'Hereford'),
  ('Whitefriars School', 'Harrow'),
  ('Whitelands Academy', 'Bicester'),
  ('Whitley Bay High School', 'Whitley Bay'),
  ('Whitmore High School', 'Harrow'),
  ('Whitstone', 'Shepton Mallet'),
  ('Whittington Green School', 'Chesterfield'),
  ('Whitworth Community High School', 'ROCHDALE'),
  ('Whitworth Park Academy', 'Spennymoor'),
  ('Whytrig Middle School', 'Whitley Bay'),
  ('Wickersley School and Sports College', 'Rotherham'),
  ('Wigmore School', 'Leominster'),
  ('Wigston Academy', 'Wigston'),
  ('Wigston College', 'Wigston'),
  ('Wildern School', 'Southampton'),
  ('Willenhall E-ACT Academy', 'Willenhall'),
  ('William Brookes School', 'Much Wenlock'),
  ('William de Ferrers School', 'Chelmsford'),
  ('William Edwards School', 'Grays'),
  ('William Ellis School', 'London'),
  ('William Farr CofE Comprehensive School', 'Lincoln'),
  ('William Howard School', 'Brampton'),
  ('William Hulme''s Grammar School', 'Manchester'),
  ('William Lovell Church of England Academy', 'Boston'),
  ('William Perkin Church of England High School', 'Greenford'),
  ('Willingdon Community School', 'Eastbourne'),
  ('Willowfield School', 'London'),
  ('Wilmington Grammar School for Boys', 'Dartford'),
  ('Wilmington Grammar School for Girls', 'Dartford'),
  ('Wilmslow High School', 'Wilmslow'),
  ('Wilson''s School', 'Wallington'),
  ('Wilsthorpe School', 'Nottingham'),
  ('Wimbledon College', 'London'),
  ('Winchcombe School', 'Cheltenham'),
  ('Winchmore School', 'London'),
  ('Windsor Girls'' School', 'Windsor'),
  ('Windsor High School and Sixth Form', 'Halesowen'),
  ('Windsor Olympus Academy', 'Birmingham'),
  ('Windsor Park CE Middle School', 'Uttoxeter'),
  ('Wingfield Academy', 'Rotherham'),
  ('Winifred Holtby Academy', 'Hull'),
  ('Winterbourne Academy', 'Bristol'),
  ('Winterhill School', 'Rotherham'),
  ('Winterstoke Hundred Academy', 'Weston-Super-Mare'),
  ('Winterton Community Academy', 'Scunthorpe'),
  ('Winton Academy', 'Bournemouth'),
  ('Wirral Grammar School for Boys', 'Wirral'),
  ('Wirral Grammar School for Girls', 'Wirral'),
  ('Witchford Village College', 'Ely'),
  ('Withernsea High School', 'Withernsea'),
  ('Witton Park Academy', 'Blackburn'),
  ('Wixams Academy', 'Bedford'),
  ('WMG Academy for Young Engineers', 'Coventry'),
  ('WMG Academy for Young Engineers (Solihull)', 'Birmingham'),
  ('Wodensborough Ormiston Academy', 'Wednesbury'),
  ('Woking High School', 'Woking'),
  ('Woldgate School and Sixth Form College', 'York'),
  ('Wolfreton School and Sixth Form College', 'Hull'),
  ('Wolgarston High School', 'Stafford'),
  ('Wollaston School', 'Wellingborough'),
  ('Wolsingham School', 'Bishop Auckland'),
  ('Wolverhampton Girls'' High School', 'Wolverhampton'),
  ('Wolverley CofE Secondary School', 'Kidderminster'),
  ('Wombourne High School', 'Wolverhampton'),
  ('Wood Green Academy', 'Wednesbury'),
  ('Wood Green School', 'Witney'),
  ('Woodbridge High School', 'Woodford Green'),
  ('Woodbrook Vale School', 'Loughborough'),
  ('Woodchurch High School', 'Wirral'),
  ('Woodcote High School', 'Coulsdon'),
  ('Woodfield Academy', 'Redditch'),
  ('Woodford County High School', 'Woodford Green'),
  ('Woodham Academy', 'Newton Aycliffe'),
  ('Woodhey High School', 'Bury'),
  ('Woodhouse Academy', 'Stoke-on-Trent'),
  ('Woodkirk Academy', 'Wakefield'),
  ('Woodland Middle School Academy', 'Bedford'),
  ('Woodlands Community College', 'Southampton'),
  ('Woodlands School', 'Basildon'),
  ('Woodmansterne School', 'London'),
  ('Woodrush High School', 'Wythall'),
  ('Woolmer Hill School', 'Haslemere'),
  ('Woolwich Polytechnic School', 'London'),
  ('Woolwich Polytechnic School for Girls', 'Thamesmead'),
  ('Wootton Park School', 'Northampton'),
  ('Wootton Upper School', 'Bedford'),
  ('Workington Academy', 'Workington'),
  ('Worle Community School', 'Weston-Super-Mare'),
  ('Worthing High School', 'Worthing'),
  ('Wreake Valley Academy', 'Leicester'),
  ('Wren Academy Enfield', 'Enfield'),
  ('Wren Academy Finchley', 'London'),
  ('Wrenn School', 'Wellingborough'),
  ('Wright Robinson College', 'Manchester'),
  ('Writhlington School', 'Radstock'),
  ('Wrotham School', 'Sevenoaks'),
  ('Wycombe High School', 'High Wycombe'),
  ('Wye School', 'Wye'),
  ('Wyedean School and Sixth Form Centre', 'Chepstow'),
  ('Wykham Park', 'Banbury'),
  ('Wymondham College', 'Wymondham'),
  ('Wymondham High Academy', 'Wymondham'),
  ('Wyvern Academy', 'Darlington'),
  ('Wyvern College', 'Eastleigh'),
  ('Wyvern St Edmund''s Academy', 'Salisbury'),
  ('XP East', 'Doncaster'),
  ('XP Gateshead', 'Felling'),
  ('XP School', 'Doncaster'),
  ('Yardleys School', 'Birmingham'),
  ('Yate Academy', 'Yate'),
  ('Yateley School', 'Yateley'),
  ('Yavneh College', 'Borehamwood'),
  ('Yesodey Hatorah Senior Girls School', 'London'),
  ('Yewlands Academy', 'Sheffield'),
  ('York High School', 'York')
ON CONFLICT (name, town) DO NOTHING;
