-- Chunk 5 of 7 (500 schools)
INSERT INTO public.schools (name, town) VALUES
  ('Preston Manor School', 'Wembley'),
  ('Preston Muslim Girls High School', 'Preston'),
  ('Preston School Academy', 'Yeovil'),
  ('Priestlands School', 'Lymington'),
  ('Priestnall School', 'Stockport'),
  ('Prince Albert High School', 'Birmingham'),
  ('Prince Henry''s High School', 'Evesham'),
  ('Prince William School', 'Oundle'),
  ('Princes Risborough School', 'Princes Risborough'),
  ('Priory Academy', 'Dunstable'),
  ('Priory Community School', 'Weston-Super-Mare'),
  ('Priory School', 'Lewes'),
  ('Priory School', 'Southsea'),
  ('Prudhoe Community High School', 'Prudhoe'),
  ('Pudsey Grammar School', 'Pudsey'),
  ('Purbrook Park School', 'Waterlooville'),
  ('Purple Ruler', 'Liverpool'),
  ('Putteridge High School', 'Luton'),
  ('Pyrland School', 'Taunton'),
  ('Q3 Academy Great Barr', 'Birmingham'),
  ('Q3 Academy Langley', 'Oldbury'),
  ('Q3 Academy Tipton', 'Tipton'),
  ('Quarrydale Academy', 'Sutton-in-Ashfield'),
  ('Queen Elizabeth Grammar School Penrith', 'Penrith'),
  ('Queen Elizabeth High School', 'Bromyard'),
  ('Queen Elizabeth High School', 'Hexham'),
  ('Queen Elizabeth School', 'Luton'),
  ('Queen Elizabeth School', ''),
  ('Queen Elizabeth Studio School', ''),
  ('Queen Elizabeth''s', 'Crediton'),
  ('Queen Elizabeth''s Academy', 'Mansfield'),
  ('Queen Elizabeth''s Girls'' School', 'Barnet'),
  ('Queen Elizabeth''s Grammar Alford - A Selective Academy', 'Alford'),
  ('Queen Elizabeth''s Grammar School', 'Faversham'),
  ('Queen Elizabeth''s Grammar School', 'Ashbourne'),
  ('Queen Elizabeth''s Grammar School', 'Blackburn'),
  ('Queen Elizabeth''s Grammar School, Horncastle', 'Horncastle'),
  ('Queen Elizabeth''s School', 'Wimborne'),
  ('Queen Elizabeth''s School, Barnet', 'Barnet'),
  ('Queen Katharine Academy', 'Peterborough'),
  ('Queen Mary''s Grammar School', 'Walsall'),
  ('Queen Mary''s High School', 'Walsall'),
  ('Queen''s Park High School', 'Chester'),
  ('Queens Park Community School', 'London'),
  ('Queens'' School', 'Bushey'),
  ('Queensbridge School', 'Birmingham'),
  ('Queensbury Academy', 'Dunstable'),
  ('Queensmead School', 'Ruislip'),
  ('Rainford High School', 'St Helens'),
  ('Rainham Mark Grammar School', 'Gillingham'),
  ('Rainham School for Girls', 'Gillingham'),
  ('Rainhill High School', 'Prescot'),
  ('Ralph Allen School', 'Bath'),
  ('Ralph Sadleir School', 'Ware'),
  ('Ralph Thoresby School', 'Leeds'),
  ('Ranelagh School', 'Bracknell'),
  ('Range High School', 'Liverpool'),
  ('Rastrick High School', 'Brighouse'),
  ('Ratton School', 'Eastbourne'),
  ('Ravens Wood School', 'Bromley'),
  ('Rawlins', 'Loughborough'),
  ('Rawmarsh Community School', 'Rotherham'),
  ('Rayner Stephens High School', 'Dukinfield'),
  ('Raynes Park High School', 'London'),
  ('Reach Academy Feltham', 'Feltham'),
  ('Reach Academy Hanworth Park', 'Feltham'),
  ('Reading Girls'' School', 'Reading'),
  ('Reading School', 'Reading'),
  ('Red House Academy', 'Sunderland'),
  ('Redborne Upper School and Community College', 'Bedford'),
  ('Redbridge Community School', 'Southampton'),
  ('Redden Court School', 'Romford'),
  ('Reddish Vale High School', 'Stockport'),
  ('Redhill Academy', 'Nottingham'),
  ('Redhill School', 'Stourbridge'),
  ('Redland Green School', 'Bristol'),
  ('Redmoor Academy', 'Hinckley'),
  ('Rednock School', 'Dursley'),
  ('Redruth School', 'Redruth'),
  ('Reepham High School and College', 'Norwich'),
  ('Regent High School', 'London'),
  ('Regents Park Community College', 'Southampton'),
  ('Reigate School', 'Reigate'),
  ('Retford Oaks Academy', 'Retford'),
  ('Rhyddings', 'Accrington'),
  ('Ribblesdale School', 'Clitheroe'),
  ('Ribston Hall High School', 'Gloucester'),
  ('Ricards Lodge High School', 'London'),
  ('Richard Challoner School', 'New Malden'),
  ('Richard Hale School', 'Hertford'),
  ('Richard Lander School', 'Truro'),
  ('Richard Rose Central Academy', 'Carlisle'),
  ('Richard Rose Morton Academy', 'Carlisle'),
  ('Richmond School & Sixth Form College', 'Richmond'),
  ('Rickmansworth School', 'Rickmansworth'),
  ('Riddlesdown Collegiate', 'Purley'),
  ('Ridgeway Academy', 'Welwyn Garden City'),
  ('Ridgeway High School', 'Prenton'),
  ('Ridgeway Secondary School', 'Redditch'),
  ('Ridgewood High School', 'Stourbridge'),
  ('Ridgewood School', 'Doncaster'),
  ('Ringwood School Academy', 'Ringwood'),
  ('Ripley St Thomas Church of England Academy', 'Lancaster'),
  ('Ripon Grammar School', 'Ripon'),
  ('Risedale School', 'Catterick Garrison'),
  ('River Academy', 'Reading'),
  ('Rivers Academy West London', 'Feltham'),
  ('Riverside School', 'Barking'),
  ('Riverside Virtual College', 'Birmingham'),
  ('Rivington and Blackrod High School', 'Bolton'),
  ('Robert Barclay Academy', 'Hoddesdon'),
  ('Robert Blake School', 'Bridgwater'),
  ('Robert Bloomfield Academy', 'Shefford'),
  ('Robert Clack School', 'Dagenham'),
  ('Robert May''s School', 'Hook'),
  ('Robertsbridge Community College', 'Robertsbridge'),
  ('Rockwood Academy', 'Birmingham'),
  ('Rodborough', 'Godalming'),
  ('Rodillian Academy', 'Wakefield'),
  ('Roding Valley High School', 'Loughton'),
  ('Rokeby School', 'London'),
  ('Ron Dearing UTC', 'Hull'),
  ('Rooks Heath School', 'Harrow'),
  ('Rosebery School', 'Epsom'),
  ('Rosedale College', 'Hayes'),
  ('Rossett School', 'Harrogate'),
  ('Rossington All Saints Academy', 'Not Yet Obtained'),
  ('Roundhay School', 'Leeds'),
  ('Roundwood Park School', 'Harpenden'),
  ('Royal Alexandra and Albert School', 'Reigate'),
  ('Royal Docks Academy', 'London'),
  ('Royal Greenwich Trust School', 'London'),
  ('Royal Latin School', 'Buckingham'),
  ('Royal Wootton Bassett Academy', 'Swindon'),
  ('Royds Hall, A Share Academy', 'Huddersfield'),
  ('Rugby Free Secondary School', 'Rugby'),
  ('Rugby High School', 'Rugby'),
  ('Rugeley John Taylor', 'Rugeley'),
  ('Ruislip High School', 'Ruislip'),
  ('Rushcliffe Spencer Academy', 'Nottingham'),
  ('Rushden Academy', 'Rushden'),
  ('Rushey Mead Academy', 'Leicester'),
  ('Ruskin Community High School', 'Crewe'),
  ('Rutlish School', 'London'),
  ('Ryburn Valley High School', 'Sowerby Bridge'),
  ('Rye College', 'Rye'),
  ('Rye Hills Academy', 'Redcar'),
  ('Ryecroft CofE Middle School', 'Rocester'),
  ('Ryedale School', 'York'),
  ('Sackville School', 'East Grinstead'),
  ('Sacred Heart Catholic Academy', 'Liverpool'),
  ('Sacred Heart Catholic High School', 'Newcastle-upon-Tyne'),
  ('Sacred Heart Catholic School', 'London'),
  ('Sacred Heart Catholic Secondary', 'Redcar'),
  ('Sacred Heart High School', 'London'),
  ('Sacred Heart of Mary Girls'' School', 'Upminster'),
  ('Saddleworth School', 'Oldham'),
  ('Saffron Walden County High School', 'Saffron Walden'),
  ('Saint Aidan''s Church of England High School', 'Poulton-le-Fylde'),
  ('Saint Ambrose College', 'Altrincham'),
  ('Saint Benedict, A Catholic Voluntary Academy', 'Derby'),
  ('Saint Cecilia''s Church of England School', 'London'),
  ('Saint Claudine''s Catholic School for Girls', 'London'),
  ('Saint Edmund Arrowsmith Catholic Academy', 'Prescot'),
  ('Saint Gabriel''s College', 'London'),
  ('Saint George Catholic Voluntary Aided College Southampton', 'Southampton'),
  ('Saint George''s Church of England School', 'Gravesend'),
  ('Saint Gregory''s Catholic College', 'Bath'),
  ('Saint Joan of Arc Catholic School', 'Rickmansworth'),
  ('Saint John Bosco College', 'London'),
  ('Saint John Henry Newman Roman Catholic College, A Voluntary Academy', 'Oldham'),
  ('Saint John Houghton Catholic Voluntary Academy', 'Ilkeston'),
  ('Saint Martin''s Catholic Voluntary Academy', 'Nuneaton'),
  ('Saint Mary Magdalene Church of England All Through School', 'London'),
  ('Saint Michael''s Catholic High School', 'Watford'),
  ('Saint Paul''s Catholic High School', 'Manchester'),
  ('Saint Pius X Catholic High School A Specialist School in Humanities', 'Rotherham'),
  ('Saints Peter and Paul Catholic High School', 'Widnes'),
  ('Sale Grammar School', 'Sale'),
  ('Sale High School', 'Sale'),
  ('Salendine Nook High School', 'Huddersfield'),
  ('Salesian School, Chertsey', 'Chertsey'),
  ('Salford City Academy', 'Manchester'),
  ('Saltash Community School', 'Saltash'),
  ('Saltley Academy', 'Birmingham'),
  ('Salvatorian Roman Catholic College', 'Harrow'),
  ('Samuel King''s School', 'Alston'),
  ('Samuel Ryder Academy', 'St Albans'),
  ('Samuel Ward Academy', 'Haverhill'),
  ('Samuel Whitbread Academy', 'Shefford'),
  ('Samworth Church Academy', 'Mansfield'),
  ('Sandbach High School and Sixth Form College', 'Sandbach'),
  ('Sandbach School', 'Sandbach'),
  ('Sanders Draper', 'Hornchurch'),
  ('Sandhill View Academy', 'Sunderland'),
  ('Sandhurst School', 'Sandhurst'),
  ('Sandringham School', 'St Albans'),
  ('Sandwell Academy', 'West Bromwich'),
  ('Sandwich Technology School', 'Sandwich'),
  ('Sandy Secondary School', 'Sandy'),
  ('Sandymoor Ormiston Academy', 'Runcorn'),
  ('Saracens High School', 'London'),
  ('Sarah Bonnell School', 'London'),
  ('Sarum Academy', 'Salisbury'),
  ('Sawston Village College', 'Cambridge'),
  ('Sawtry Village Academy', 'Huntingdon'),
  ('Scalby Academy', 'Scarborough'),
  ('Scarborough University Technical College', 'Scarborough'),
  ('School 21', 'Stratford'),
  ('School of Science and Technology Maidstone', 'Maidstone'),
  ('Scissett Middle School', 'Huddersfield'),
  ('Scott Medical and Healthcare College', 'Plymouth'),
  ('Seaford Head School', 'Seaford'),
  ('Seaham High School', 'Seaham'),
  ('Seahaven Academy', 'Newhaven'),
  ('Seaton Sluice Middle School', 'Whitley Bay'),
  ('Seaton Valley High School', 'Seaton Delaval'),
  ('Sedgefield Community College', 'Stockton-on-Tees'),
  ('Sedgehill Academy', 'London'),
  ('Selby High School Specialist School for the Arts and Science', 'Selby'),
  ('Selly Park Girls'' School', 'Birmingham'),
  ('Selston High School', 'Nottingham'),
  ('Selwood Academy', 'Frome'),
  ('Serlby Park Academy', 'Doncaster'),
  ('Settle College', 'Settle'),
  ('Settlebeck School', 'Sedbergh'),
  ('Seva School', 'Coventry'),
  ('Seven Kings School', 'Ilford'),
  ('Severn Vale School', 'Gloucester'),
  ('Sewell Park Academy', 'Norwich'),
  ('Sexey''s School', 'Bruton'),
  ('SGS Berkeley Green UTC', 'Berkeley'),
  ('SGS Forest High School', 'Cinderford'),
  ('Shaftesbury School', 'Shaftesbury'),
  ('Sharnbrook Academy', 'Bedford'),
  ('Sharples School', 'Bolton'),
  ('Shavington Academy', 'Shavington'),
  ('Sheffield Park Academy', 'Sheffield'),
  ('Sheffield Springs Academy', 'Sheffield'),
  ('Sheldon School', 'Chippenham'),
  ('Shelley College, A Share Academy', 'Huddersfield'),
  ('Shenfield High School', 'Brentwood'),
  ('Shenley Brook End School', 'Milton Keynes'),
  ('Sherburn High School', 'Leeds'),
  ('Sheringham High School', 'Sheringham'),
  ('Shevington High School', 'Wigan'),
  ('Shipston High School', 'Shipston-on-Stour'),
  ('Shire Oak Academy', 'Walsall'),
  ('Shirebrook Academy', 'Mansfield'),
  ('Shireland Biomedical Utc', 'West Bromwich'),
  ('Shireland CBSO Academy', 'West Bromwich'),
  ('Shireland Collegiate Academy', 'Smethwick'),
  ('Shirley High School Performing Arts College', 'Croydon'),
  ('Shoeburyness High School', 'Southend-on-Sea'),
  ('Shoreham Academy', 'Shoreham-by-Sea'),
  ('Shrewsbury Academy', 'Shrewsbury'),
  ('Shuttleworth College', 'Burnley'),
  ('Sidmouth College', 'Sidmouth'),
  ('Sidney Stringer Academy', 'Coventry'),
  ('Silverdale School', 'Sheffield'),
  ('Silverstone UTC', 'Towcester'),
  ('Simon Balle All-Through School', 'Hertford'),
  ('Simon Langton Girls'' Grammar School', 'Canterbury'),
  ('Simon Langton Grammar School for Boys', 'Canterbury'),
  ('Sir Bernard Lovell Academy', 'Bristol'),
  ('Sir Christopher Hatton Academy', 'Wellingborough'),
  ('Sir Frederick Gibberd College', 'Harlow'),
  ('Sir Geoffrey Leigh Academy', 'Dartford'),
  ('Sir Graham Balfour High School', 'Stafford'),
  ('Sir Harry Smith Community College', 'Peterborough'),
  ('Sir Henry Floyd Grammar School', 'Aylesbury'),
  ('Sir James Smith''s School', 'Camelford'),
  ('Sir John Hunt Community Sports College', 'Plymouth'),
  ('Sir John Lawes School', 'Harpenden'),
  ('Sir John Leman High School', 'Beccles'),
  ('Sir John Nelthorpe School', 'Brigg'),
  ('Sir John Talbot''s School', 'Whitchurch'),
  ('Sir John Thursby Community College', 'Burnley'),
  ('Sir Jonathan North Girls'' College', 'Leicester'),
  ('Sir Joseph Williamson''s Mathematical School', 'Rochester'),
  ('Sir Robert Pattinson Academy', 'Lincoln'),
  ('Sir Roger Manwood''s School', 'Sandwich'),
  ('Sir Thomas Boteler Church of England High School', 'Warrington'),
  ('Sir Thomas Boughey Academy', 'Stoke-on-Trent'),
  ('Sir Thomas Fremantle School', 'Winslow'),
  ('Sir Thomas Rich''s School', 'Gloucester'),
  ('Sir Thomas Wharton Academy', 'Doncaster'),
  ('Sir William Borlase''s Grammar School', 'Marlow'),
  ('Sir William Ramsay School', 'High Wycombe'),
  ('Sir William Robertson Academy, Welbourn', 'Lincoln'),
  ('Sir William Romney''s School', 'Tetbury'),
  ('Sir William Stanier School', 'Crewe'),
  ('Sirius Academy North', 'Hull'),
  ('Sirius Academy West', 'Hull'),
  ('Skegness Academy', 'Skegness'),
  ('Skegness Grammar School', 'Skegness'),
  ('Skinners'' Academy', 'London'),
  ('Skinners'' Kent Academy', 'Tunbridge Wells'),
  ('Skipton Girls'' High School', 'Skipton'),
  ('Slough and Eton Church of England Business and Enterprise College', 'Slough'),
  ('Small Heath Leadership Academy', 'Birmingham'),
  ('Smestow Academy', 'Wolverhampton'),
  ('Smith''s Wood Academy', 'Birmingham'),
  ('Smithdon High School', 'Hunstanton'),
  ('Smithills School', 'Bolton'),
  ('Soar Valley College', 'Leicester'),
  ('Soham Village College', 'Ely'),
  ('Solway Community School', 'Wigton'),
  ('Somercotes Academy', 'Louth'),
  ('Somerset Studio School', 'Radstock'),
  ('Somervale Secondary School', 'Radstock'),
  ('Sophia High School', 'London'),
  ('South Axholme Academy', 'Doncaster'),
  ('South Bank University Academy', 'London'),
  ('South Bromsgrove High', 'Bromsgrove'),
  ('South Charnwood High School', 'Markfield'),
  ('South Chingford Foundation School', 'London'),
  ('South Craven School', 'Keighley'),
  ('South Dartmoor Community College', 'Ashburton'),
  ('South Devon UTC', 'Newton Abbot'),
  ('South Hunsley School and Sixth Form College', 'North Ferriby'),
  ('South Molton Community College', 'South Molton'),
  ('South Nottinghamshire Academy', 'Nottingham'),
  ('South Shore Academy', 'Blackpool'),
  ('South Wigston High School', 'Wigston'),
  ('South Wilts Grammar School', 'Salisbury'),
  ('South Wirral High School', 'Wirral'),
  ('Southam College', 'Southam'),
  ('Southborough High School', 'Surbiton'),
  ('Southchurch High School', 'Southend-On-Sea'),
  ('Southend High School for Boys', 'Southend-on-Sea'),
  ('Southend High School for Girls', 'Southend-on-Sea'),
  ('Southfield School for Girls', 'Kettering'),
  ('Southfields Academy', 'London'),
  ('Southgate School', 'Barnet'),
  ('Southlands High School', 'Chorley'),
  ('Southmoor Academy', 'Sunderland'),
  ('Space Studio West London', 'Hounslow'),
  ('Spalding Academy', 'Spalding'),
  ('Spalding Grammar School', 'Spalding'),
  ('Spalding High School', 'Spalding'),
  ('Spen Valley High School', 'Liversedge'),
  ('Sponne School', 'Towcester'),
  ('Springfield School', 'Portsmouth'),
  ('Springwell Community College', 'Chesterfield'),
  ('Springwest Academy', 'Feltham'),
  ('Springwood High School', 'King''s Lynn'),
  ('Sprowston Community Academy', 'Norwich'),
  ('Ss John Fisher and Thomas More Roman Catholic High School', 'Colne'),
  ('St Aidan''s Catholic Academy', 'Sunderland'),
  ('St Aidan''s Church of England Academy', 'Darlington'),
  ('St Aidan''s Church of England High School', 'Harrogate'),
  ('St Alban''s Catholic High School', 'Ipswich'),
  ('St Albans Girls'' School', 'St Albans'),
  ('St Aldhelm''s Academy', 'Poole'),
  ('St Aloysius'' College', 'London'),
  ('St Ambrose Barlow RC High School', 'Manchester'),
  ('St Andrew the Apostle Greek Orthodox School', 'London'),
  ('St Andrew''s Catholic School', 'Leatherhead'),
  ('St Andrew''s CofE High School', 'Worthing'),
  ('St Angela''s Ursuline School', 'London'),
  ('St Anne''s Catholic High School for Girls', 'London'),
  ('St Anne''s Catholic School', 'Southampton'),
  ('St Anne''s Church of England Academy', 'Manchester'),
  ('St Anne''s RC Voluntary Academy', 'Stockport'),
  ('St Anselm''s Catholic School, Canterbury', 'Canterbury'),
  ('St Anselm''s College', 'Prenton'),
  ('St Anthony''s Girls'' Catholic Academy', 'Sunderland'),
  ('St Antony''s Roman Catholic School, a Voluntary Academy', 'Manchester'),
  ('St Augustine Academy', 'Maidstone'),
  ('St Augustine of Canterbury Catholic Academy', 'St. Helens'),
  ('St Augustine''s Catholic College', 'Trowbridge'),
  ('St Augustine''s Catholic High School', 'Redditch'),
  ('St Augustine''s Catholic School - a Catholic voluntary academy', 'Scarborough'),
  ('St Augustine''s Federated Schools: CE High School', 'London'),
  ('St Augustine''s Roman Catholic High School, a Voluntary Academy', 'Clitheroe'),
  ('St Bartholomew''s School', 'Newbury'),
  ('St Bede''s and St Joseph''s Catholic College, A Voluntary Academy', 'Bradford'),
  ('St Bede''s Catholic College', 'Bristol'),
  ('St Bede''s Catholic High School', 'Ormskirk'),
  ('St Bede''s Catholic High School, Lytham', 'Lytham St Annes'),
  ('St Bede''s Catholic Middle School', 'Redditch'),
  ('St Bede''s Catholic School and Byron Sixth Form College', 'Peterlee'),
  ('St Bede''s Catholic School and Sixth Form College, Lanchester', 'Durham'),
  ('St Bede''s Catholic Voluntary Academy', 'Scunthorpe'),
  ('St Bede''s Inter-Church School', 'Cambridge'),
  ('St Bede''s Roman Catholic High School, Blackburn', 'Blackburn'),
  ('St Bede''s School', 'Redhill'),
  ('St Benedict''s Catholic College', 'Colchester'),
  ('St Benedict''s Catholic High School', 'Whitehaven'),
  ('St Benedict''s Catholic High School', 'Alcester'),
  ('St Benedict''s Catholic School', 'Bury St Edmunds'),
  ('St Benet Biscop Catholic Academy', 'Bedlington'),
  ('St Bernadette Catholic Secondary School', 'Bristol'),
  ('St Bernard''s Catholic Grammar School', 'Slough'),
  ('St Bernard''s Catholic High School', 'Rotherham'),
  ('St Bernard''s High School', 'Westcliff-on-Sea'),
  ('St Bernards Catholic High School, Barrow', 'Barrow-in-Furness'),
  ('St Birinus School', 'Didcot'),
  ('St Bonaventure''s RC School', 'London'),
  ('St Boniface''s RC College', 'Plymouth'),
  ('St Catherine''s Catholic School', 'Bexleyheath'),
  ('St Catherine''s College', 'Eastbourne'),
  ('St Cecilia''s RC High School', 'Preston'),
  ('St Clement Danes School', 'Rickmansworth'),
  ('St Clement''s High School', 'King''s Lynn'),
  ('St Clere''s School', 'Stanford-le-Hope'),
  ('St Columba''s Catholic Boys'' School', 'Bexleyheath'),
  ('St Crispin''s School', 'Wokingham'),
  ('St Cuthbert Mayne School', 'Torquay'),
  ('St Cuthbert''s Catholic High School', 'St Helens'),
  ('St Cuthbert''s High School', 'Newcastle-upon-Tyne'),
  ('St Cuthbert''s Roman Catholic High School, a Voluntary Academy', 'Rochdale'),
  ('St Damian''s RC Science College', 'Ashton-under-Lyne'),
  ('St Dunstan''s School', 'Glastonbury'),
  ('St Edmund Arrowsmith Catholic High School, Ashton-in-Makerfield', 'Wigan'),
  ('St Edmund Campion Catholic School', 'Birmingham'),
  ('St Edmund''s Catholic Academy', 'Wolverhampton'),
  ('St Edmund''s Catholic School', 'Portsmouth'),
  ('St Edmund''s Catholic School', 'Dover'),
  ('St Edward''s Church of England Academy', 'Leek'),
  ('St Edward''s Church of England Academy', 'Romford'),
  ('St Edward''s College', 'Liverpool'),
  ('St Edward''s Roman Catholic/Church of England School, Poole', 'Poole'),
  ('St Edward''s Royal Free Ecumenical Middle School, Windsor', 'Windsor'),
  ('St Egwin''s CofE Middle School', 'Evesham'),
  ('St Francis of Assisi Catholic College', 'Walsall'),
  ('St Francis Xavier School - a Joint Catholic and Church of England Voluntary Academy', 'Richmond'),
  ('St Francis Xavier''s Catholic Academy', 'Liverpool'),
  ('St Gabriel''s RC High School, a Voluntary Academy', 'Bury'),
  ('St George''s Academy', 'Sleaford'),
  ('St George''s Catholic School', 'London'),
  ('St George''s Church of England Foundation School', 'Broadstairs'),
  ('St George''s School', 'Harpenden'),
  ('St George''s School A Church of England Academy', 'Blackpool'),
  ('St Gregory''s Catholic High School', 'Warrington'),
  ('St Gregory''s Catholic School', 'Tunbridge Wells'),
  ('St Gregory''s Catholic Science College', 'Harrow'),
  ('St Helena School', 'Colchester'),
  ('St Hild''s Church of England School', 'Hartlepool'),
  ('St Hilda''s Church of England High School', 'Liverpool'),
  ('St Ignatius College', 'Enfield'),
  ('St Ives School', 'St Ives'),
  ('St Ivo Academy', 'St Ives'),
  ('St James Academy', 'Dudley'),
  ('St James School', 'Exeter'),
  ('St James'' Catholic High School', 'London'),
  ('St James'' Catholic High School', 'Cheadle'),
  ('St James''s Church of England High School', 'Bolton'),
  ('St John Bosco Arts College', 'Croxteth'),
  ('St John Fisher Catholic Academy', 'Harrogate'),
  ('St John Fisher Catholic College', 'Newcastle Under Lyme'),
  ('St John Fisher Catholic Comprehensive School', 'Rochester'),
  ('St John Fisher Catholic High School', 'Wigan'),
  ('St John Fisher Catholic High School', 'Peterborough'),
  ('St John Fisher Catholic Voluntary Academy', 'Dewsbury'),
  ('St John Henry Newman Catholic School', 'Carlisle'),
  ('St John Payne Catholic School, Chelmsford', 'Chelmsford'),
  ('St John Plessington Catholic College', 'Wirral'),
  ('St John the Baptist Catholic Comprehensive School, Woking', 'Woking'),
  ('St John Wall Catholic School', 'Birmingham'),
  ('St John''s Catholic Comprehensive', 'Gravesend'),
  ('St John''s Catholic School & Sixth Form College', 'Bishop Auckland'),
  ('St John''s Church of England Middle School Academy', 'Bromsgrove'),
  ('St John''s Marlborough', 'Marlborough'),
  ('St Johns CofE Academy', 'Wantage'),
  ('St Joseph''s Catholic Academy', 'Hebburn'),
  ('St Joseph''s Catholic College', 'Swindon'),
  ('St Joseph''s Catholic High School', 'Slough'),
  ('St Joseph''s Catholic Middle School, Hexham', 'Hexham'),
  ('St Joseph''s Catholic School', 'Salisbury'),
  ('St Joseph''s College', 'Stoke-on-Trent'),
  ('St Joseph''s College', 'London'),
  ('St Joseph''s RC High School', 'Bolton'),
  ('St Josephs Catholic High School, Workington', 'Workington'),
  ('St Julie''s Catholic High School', 'Liverpool'),
  ('St Katherine''s School', 'Bristol'),
  ('St Laurence School', 'Bradford-on-Avon'),
  ('St Leonard''s Catholic School, Durham', 'Durham'),
  ('St Luke''s Church of England School', 'Exeter'),
  ('St Margaret Ward Catholic Academy', 'Stoke-on-Trent'),
  ('St Margaret''s Church of England Academy', 'Liverpool'),
  ('St Mark''s Catholic School', 'Hounslow'),
  ('St Mark''s Church of England Academy', 'Mitcham'),
  ('St Mark''s Church of England School', 'Southampton'),
  ('St Mark''s CofE School', 'Bath'),
  ('St Mark''s West Essex Catholic School', 'Harlow'),
  ('St Martin''s School Brentwood', 'Brentwood'),
  ('St Martins School (3-16 Learning Community)', 'Oswestry'),
  ('St Mary Magdalene Academy', 'London'),
  ('St Mary Redcliffe and Temple School', 'Bristol'),
  ('St Mary''s and St John''s CofE School', 'London'),
  ('St Mary''s Catholic Academy', 'Blackpool'),
  ('St Mary''s Catholic College, A Voluntary Academy', 'Wallasey'),
  ('St Mary''s Catholic High School', 'Croydon'),
  ('St Mary''s Catholic High School', 'Manchester'),
  ('St Mary''s Catholic High School', 'Leyland'),
  ('St Mary''s Catholic High School, A Catholic Voluntary Academy', 'Chesterfield'),
  ('St Mary''s Catholic School', 'Newcastle-upon-Tyne'),
  ('St Mary''s Catholic School', 'Bishop''s Stortford')
ON CONFLICT (name, town) DO NOTHING;
