-- Chunk 3 of 7 (500 schools)
INSERT INTO public.schools (name, town) VALUES
  ('Great Torrington School', 'Torrington'),
  ('Great Western Academy', 'Swindon'),
  ('Great Wyrley Academy', 'Walsall'),
  ('Great Yarmouth Charter Academy', 'Great Yarmouth'),
  ('Greater Peterborough UTC', 'Peterborough'),
  ('Greatfields School', 'Barking'),
  ('Greenacre School', 'Chatham'),
  ('Greenbank High School', 'Southport'),
  ('Greenfield Academy', 'Newton Aycliffe'),
  ('Greenford High School', 'Southall'),
  ('Greenshaw High School', 'Sutton'),
  ('Greig City Academy', 'London'),
  ('Grey Court School', 'Richmond'),
  ('Greyfriars Catholic School', 'Oxford'),
  ('Grove Academy', 'Slough'),
  ('Guildford County School', 'Guildford'),
  ('Guilsborough Academy', 'Northampton'),
  ('Guiseley School', 'Leeds'),
  ('Gumley House RC Convent School, FCJ', 'Isleworth'),
  ('Gunnersbury Catholic School', 'Brentford'),
  ('Guru Nanak Sikh Academy', 'Hayes'),
  ('Haberdashers'' Abraham Darby', 'Telford'),
  ('Haberdashers'' Adams', 'Newport'),
  ('Haberdashers'' Borough Academy', 'London'),
  ('Haberdashers'' Crayford Academy', 'Dartford'),
  ('Haberdashers'' Hatcham College', 'London'),
  ('Haberdashers'' Knights Academy', 'Bromley'),
  ('Hadleigh High School', 'Ipswich'),
  ('Hadley Learning Community - Secondary Phase', 'Telford'),
  ('Hadlow Rural Community School', 'Hadlow'),
  ('Haggerston School', 'London'),
  ('Hagley Catholic High School', 'Hagley'),
  ('Haileybury Turnford', 'Waltham Cross'),
  ('Hailsham Academy', 'Hailsham'),
  ('Halewood Academy', 'Knowsley'),
  ('Hall Cross Academy', 'Doncaster'),
  ('Hall Green School', 'Birmingham'),
  ('Hall Mead School', 'Upminster'),
  ('Hall Park Academy', 'Nottingham'),
  ('Hammersmith Academy', 'London'),
  ('Hampstead School', 'London'),
  ('Hampton College', 'Peterborough'),
  ('Hampton Gardens Secondary School', 'Peterborough'),
  ('Hampton High', 'Hampton'),
  ('Hamstead Hall Academy', 'Birmingham'),
  ('Handsworth Grange Community Sports College', 'Sheffield'),
  ('Hanham Woods Academy', 'Bristol'),
  ('Hanley Castle High School', 'Worcester'),
  ('Hans Price Academy', 'Weston-super-Mare'),
  ('Hanson Academy', 'Bradford'),
  ('Harborne Academy', 'Birmingham'),
  ('Hardenhuish School', 'Chippenham'),
  ('Harefield School', 'Uxbridge'),
  ('Harlington School', 'Hayes'),
  ('Harlington Upper School', 'Dunstable'),
  ('Harper Green School', 'Bolton'),
  ('Harris Academy Battersea', 'London'),
  ('Harris Academy Beckenham', 'Beckenham'),
  ('Harris Academy Bermondsey', 'London'),
  ('Harris Academy Beulah Hill', 'London'),
  ('Harris Academy Chafford Hundred', 'Grays'),
  ('Harris Academy Chobham', 'London'),
  ('Harris Academy Clapham', 'London'),
  ('Harris Academy Falconwood', 'Welling'),
  ('Harris Academy Greenwich', 'London'),
  ('Harris Academy Merton', 'Mitcham'),
  ('Harris Academy Morden', 'Morden'),
  ('Harris Academy Ockendon', 'South Ockendon'),
  ('Harris Academy Orpington', ''),
  ('Harris Academy Peckham', 'London'),
  ('Harris Academy Purley', 'South Croydon'),
  ('Harris Academy Rainham', 'Rainham'),
  ('Harris Academy Riverside', 'Purfleet'),
  ('Harris Academy South Norwood', 'London'),
  ('Harris Academy St John''s Wood', 'London'),
  ('Harris Academy Sutton', 'Sutton'),
  ('Harris Academy Tottenham', 'London'),
  ('Harris Academy Wimbledon', 'London'),
  ('Harris Boys'' Academy East Dulwich', 'London'),
  ('Harris Church of England Academy', 'Rugby'),
  ('Harris City Academy Crystal Palace', 'London'),
  ('Harris Garrard Academy', 'Erith'),
  ('Harris Girls Academy Bromley', 'Beckenham'),
  ('Harris Girls'' Academy East Dulwich', 'London'),
  ('Harris Invictus Academy Croydon', 'Croydon'),
  ('Harris Lowe Academy Willesden', 'London'),
  ('Harris Science Academy East London', 'London'),
  ('Harrogate Grammar School', 'Harrogate'),
  ('Harrogate High School', 'Harrogate'),
  ('Harrow High School', 'Harrow'),
  ('Harrow Way Community School', 'Andover'),
  ('Harrytown Catholic High School', 'Stockport'),
  ('Hartford Church of England High School', 'Northwich'),
  ('Hartismere School', 'Eye'),
  ('Hartland High School', 'Reading'),
  ('Harton Academy', 'South Shields'),
  ('Hartsdown Academy', 'Margate'),
  ('Hartshill Academy', 'Nuneaton'),
  ('Harwich and Dovercourt High School', 'Harwich'),
  ('Haslingden High School and Sixth Form', 'Rossendale'),
  ('Hasmonean High School for Boys', 'London'),
  ('Hasmonean High School for Girls', 'London'),
  ('Hastings High School', 'Hinckley'),
  ('Hatch End High School', 'Harrow'),
  ('Haughton Academy', 'Darlington'),
  ('Havant Academy', 'Havant'),
  ('Havelock Academy', 'Grimsby'),
  ('Haven High Academy', 'Boston'),
  ('Haverstock School', 'London'),
  ('Hawkley Hall High School', 'Wigan'),
  ('Haybridge High School and Sixth Form', 'Stourbridge'),
  ('Haydon Bridge High School', 'Hexham'),
  ('Haydon School', 'Pinner'),
  ('Hayes School', 'Bromley'),
  ('Hayesfield Girls School', 'Bath'),
  ('Haygrove School', 'Bridgwater'),
  ('Hayle Academy', 'Hayle'),
  ('Haywood Academy', 'Stoke-on-Trent'),
  ('Hazel Grove High School', 'Stockport'),
  ('Hazel Wood High School', 'Bury'),
  ('Hazelwick School', 'Crawley'),
  ('Headlands School', 'Bridlington'),
  ('Healing Academy', 'Grimsby'),
  ('Heanor Gate Spencer Academy', 'Heanor'),
  ('Heart of England School', 'Coventry'),
  ('Heartlands High School', 'London'),
  ('Heath Lane Academy', 'Leicester'),
  ('Heath Park', 'Wolverhampton'),
  ('Heathcote School & Science College', 'London'),
  ('Heathfield Community College', 'Heathfield'),
  ('Heathside School', 'Weybridge'),
  ('Heathside Walton-on-Thames', 'Walton-on-Thames'),
  ('Hebburn Comprehensive School', 'Hebburn'),
  ('Heckmondwike Grammar School', 'Heckmondwike'),
  ('Hedingham School and Sixth Form', 'Halstead'),
  ('Hele''s School', 'Plymouth'),
  ('Helena Romanes School', 'Great Dunmow'),
  ('Hellesdon High School', 'Norwich'),
  ('Helsby High School', 'Frodsham'),
  ('Helston Community College', 'Helston'),
  ('Hendon School', 'London'),
  ('Henley Bank High School', 'Gloucester'),
  ('Henley In Arden School', 'Henley-in-Arden'),
  ('Henlow Church of England Academy', 'Henlow'),
  ('Henry Beaufort School', 'Winchester'),
  ('Heritage High School', 'Chesterfield'),
  ('Hermitage Academy', 'Chester le Street'),
  ('Herne Bay High School', 'Herne Bay'),
  ('Heron Hall Academy', 'Enfield'),
  ('Herschel Grammar School', 'Slough'),
  ('Hertswood Academy', 'Borehamwood'),
  ('Hessle High School and Penshurst Primary School', 'Hessle'),
  ('Heston Community School', 'Hounslow'),
  ('Hethersett Academy', 'Norwich'),
  ('Hetton Academy', 'Houghton le Spring'),
  ('Hewens College', 'Hayes'),
  ('Hewett Academy', 'Norwich'),
  ('Heworth Grange School', 'Gateshead'),
  ('Hexham Middle School', 'Hexham'),
  ('Heyford Park School', 'Bicester'),
  ('High Storrs School', 'Sheffield'),
  ('High Tunstall College of Science', 'Hartlepool'),
  ('Higham Lane North Academy', 'Nuneaton'),
  ('Higham Lane School', 'Nuneaton'),
  ('Highams Park School', 'London'),
  ('Highbury Fields School', 'London'),
  ('Highcliffe School', 'Christchurch'),
  ('Highdown School and Sixth Form Centre', 'Reading'),
  ('Highfield Leadership Academy', 'Blackpool'),
  ('Highfield Middle School', 'Prudhoe'),
  ('Highfields School', 'Wolverhampton'),
  ('Highfields School', 'Matlock'),
  ('Highgate Wood Secondary School', 'London'),
  ('Highlands School', 'London'),
  ('Highsted Grammar School', 'Sittingbourne'),
  ('Highworth Grammar School', 'Ashford'),
  ('Highworth Warneford School', 'Swindon'),
  ('Hilbre High School', 'Wirral'),
  ('Hillcrest School and Sixth Form Centre', 'Birmingham'),
  ('Hillside High School', 'Bootle'),
  ('Hillview School for Girls', 'Tonbridge'),
  ('Hinchingbrooke School', 'Huntingdon'),
  ('Hinchley Wood School', 'Esher'),
  ('Hinde House 2-16 Academy', 'Sheffield'),
  ('Hitchin Boys'' School', 'Hitchin'),
  ('Hitchin Girls'' School', 'Hitchin'),
  ('Hobart High School', 'Norwich'),
  ('Hockerill Anglo-European College', 'Bishop''s Stortford'),
  ('Hodge Hill College', 'Birmingham'),
  ('Hodge Hill Girls'' School', 'Birmingham'),
  ('Hodgson Academy', 'Poulton-Le-Fylde'),
  ('Hoe Valley School', 'Woking'),
  ('Holbrook Academy', 'Ipswich'),
  ('Holcombe Grammar School', 'Chatham'),
  ('Holderness Academy', 'Hull'),
  ('Holland Park School', 'London'),
  ('Hollingworth Academy', 'Rochdale'),
  ('Holly Lodge Girls'' College', 'Liverpool'),
  ('Holly Lodge High School College of Science', 'Smethwick'),
  ('Holmer Green Senior School', 'High Wycombe'),
  ('Holmes Chapel Comprehensive School', 'Crewe'),
  ('Holmfirth High School', 'Holmfirth'),
  ('Holmleigh Park High School', 'Gloucester'),
  ('Holsworthy Community College', 'Holsworthy'),
  ('Holte School', 'Birmingham'),
  ('Holy Cross Catholic High School', 'Chorley'),
  ('Holy Family Catholic High School', 'Liverpool'),
  ('Holy Family Catholic School', 'London'),
  ('Holy Family Roman Catholic and Church of England College', 'Heywood'),
  ('Holy Trinity Academy', 'Telford'),
  ('Holy Trinity Catholic and Church of England School', 'Barnsley'),
  ('Holy Trinity Catholic School', 'Birmingham'),
  ('Holy Trinity CofE Secondary School, Crawley', 'Crawley'),
  ('Holy Trinity School', 'Kidderminster'),
  ('Holyhead School', 'Birmingham'),
  ('Holyport College', 'Holyport'),
  ('Holyrood Academy', 'Chard'),
  ('Holywell School', 'Bedford'),
  ('Homewood School and Sixth Form Centre', 'Tenterden'),
  ('Honiton Community College', 'Honiton'),
  ('Honley High School', 'Holmfirth'),
  ('Honywood School', 'Colchester'),
  ('Hope Academy', 'Newton-le-Willows'),
  ('Hope Valley College', 'Hope Valley'),
  ('Horbury Academy', 'Wakefield'),
  ('Horizon Community College', 'Barnsley'),
  ('Hornchurch High School', 'Hornchurch'),
  ('Horndean Technology College', 'Waterlooville'),
  ('Hornsea School and Language College', 'Hornsea'),
  ('Hornsey School for Girls', 'London'),
  ('Horsforth School', 'Leeds'),
  ('Houlton School', 'RUGBY'),
  ('Hounsdown School', 'Southampton'),
  ('Houstone School', 'Dunstable'),
  ('Hove Park School and Sixth Form Centre', 'Hove'),
  ('Howard of Effingham School', 'Leatherhead'),
  ('Howden School', 'Goole'),
  ('Hugh Sexey Church of England Middle School', 'Wedmore'),
  ('Huish Episcopi Academy', 'LANGPORT'),
  ('Hull Trinity House Academy', 'Hull'),
  ('Humberston Academy', 'Grimsby'),
  ('Hummersknott Academy', 'Darlington'),
  ('Humphrey Perkins School', 'Loughborough'),
  ('Humphry Davy School', 'Penzance'),
  ('Hungerhill School', 'Doncaster'),
  ('Huntcliff School', 'Saltburn By the Sea'),
  ('Huntington School', 'York'),
  ('Hurstmere School', 'Sidcup'),
  ('Hurworth School', 'Darlington'),
  ('Hutton Church of England Grammar School', 'Preston'),
  ('Huxlow Academy', 'Irthlingborough'),
  ('Hyde High School', 'Hyde'),
  ('Hylands School', 'Chelmsford'),
  ('Ian Ramsey Church of England Academy', 'Stockton-on-Tees'),
  ('Ibstock School', 'Ibstock'),
  ('Iceni Secondary Academy', 'Thetford'),
  ('Icknield Community College', 'Watlington'),
  ('Icknield High School', 'Luton'),
  ('Idsall School', 'Shifnal'),
  ('Ifield Community College', 'Crawley'),
  ('IKB Academy', 'Bristol'),
  ('Ilford County High School', 'Ilford'),
  ('Ilkley Grammar School', 'Ilkley'),
  ('Imberhorne School', 'East Grinstead'),
  ('Immanuel College', 'Bradford'),
  ('Impington Village College', 'Cambridge'),
  ('Ingleby Manor Free School', 'Stockton-on-Tees'),
  ('International British Online School', ''),
  ('Invicta Grammar School', 'Maidstone'),
  ('Ipsley CofE Middle School', 'Redditch'),
  ('Ipswich Academy', 'Ipswich'),
  ('Irlam and Cadishead Academy', 'Manchester'),
  ('Isca Academy', 'Exeter'),
  ('Isleworth and Syon School for Boys', 'Isleworth'),
  ('Islip Manor High School', 'Northolt'),
  ('Ivanhoe School', 'Ashby-de-la-Zouch'),
  ('Iveshead School', 'Loughborough'),
  ('Ivybridge Community College', 'Ivybridge'),
  ('Ixworth High School', 'Ixworth'),
  ('Jack Hunt Academy', 'Peterborough'),
  ('James Bateman Middle School', 'Biddulph'),
  ('James Calvert Spence College', 'Morpeth'),
  ('Jane Austen College', 'Norwich'),
  ('Jarrow School', 'Jarrow'),
  ('JCoSS', 'New Barnet'),
  ('Jesmond Park Academy', 'Newcastle-upon-Tyne'),
  ('Jewellery Quarter Academy', 'Birmingham'),
  ('JFS', 'Harrow'),
  ('Jo Richardson Community School', 'Dagenham'),
  ('John Cabot Academy', 'Bristol'),
  ('John Colet School', 'Aylesbury'),
  ('John F Kennedy Catholic School', 'Hemel Hempstead'),
  ('John Ferneley College', 'Melton Mowbray'),
  ('John Flamsteed Community School', 'Ripley'),
  ('John Hampden Grammar School', 'High Wycombe'),
  ('John Hanson Community School', 'Andover'),
  ('John Henry Newman Catholic College', 'Birmingham'),
  ('John Kyrle High School and Sixth Form Centre Academy', 'Ross-on-Wye'),
  ('John Masefield High School', 'Ledbury'),
  ('John Mason School', 'Abingdon'),
  ('John O''Gaunt School', 'Hungerford'),
  ('John Port Spencer Academy', 'Derby'),
  ('John Ruskin School', 'Coniston'),
  ('John Smeaton Academy', 'Leeds'),
  ('John Spence Community High School', 'North Shields'),
  ('John Spendluffe Foundation Technology College', 'Alford'),
  ('John Taylor Free School', 'Burton-on-Trent'),
  ('John Taylor High School', 'Burton-on-Trent'),
  ('John Whitgift Academy', 'Grimsby'),
  ('Joseph Leckie Academy', 'Walsall'),
  ('Joseph Rowntree School', 'York'),
  ('Joyce Frankland Academy, Newport', 'Saffron Walden'),
  ('Jubilee High School', 'Addlestone'),
  ('Judgemeadow Community College', 'Leicester'),
  ('Katharine Lady Berkeley''s School', 'Wotton-under-Edge'),
  ('Katherine Warington School', 'Harpenden'),
  ('Kearsley Academy', 'Bolton'),
  ('Kelmscott School', 'London'),
  ('Kelvin Hall School', 'Hull'),
  ('Kemnal Technology College', 'Sidcup'),
  ('Kempston Academy', 'Bedford'),
  ('Ken Stimpson Academy', 'Peterborough'),
  ('Kendrick School', 'Reading'),
  ('Kenilworth School and Sixth Form', 'Kenilworth'),
  ('Kennet School', 'Thatcham'),
  ('Kensington Aldridge Academy', 'London'),
  ('Kenton School', 'Newcastle-upon-Tyne'),
  ('Kents Hill Park all-through school', 'Milton Keynes'),
  ('Kepier', 'Houghton le Spring'),
  ('Kesgrave High School', 'Ipswich'),
  ('Kesteven and Grantham Girls'' School', 'Grantham'),
  ('Kesteven and Sleaford High School Selective Academy', 'Sleaford'),
  ('Keswick School', 'Keswick'),
  ('Kettering Buccleuch Academy', 'Kettering'),
  ('Kettering Science Academy', 'Kettering'),
  ('Kettlethorpe High School', 'Wakefield'),
  ('Kibworth Mead Academy', 'Leicester'),
  ('Kidsgrove Secondary School', 'Stoke-on-Trent'),
  ('Kineton High School', 'Warwick'),
  ('King Alfred''s', 'Wantage'),
  ('King Arthur''s School', 'Wincanton'),
  ('King Charles I School', 'Kidderminster'),
  ('King David High School', 'Liverpool'),
  ('King Ecgbert School', 'Sheffield'),
  ('King Edward VI Academy', 'Spilsby'),
  ('King Edward VI Aston School', 'Birmingham'),
  ('King Edward VI Balaam Wood Academy', 'Birmingham'),
  ('King Edward VI Camp Hill School for Boys', 'Birmingham'),
  ('King Edward VI Camp Hill School for Girls', 'Birmingham'),
  ('King Edward VI CEVC School', 'Bury St Edmunds'),
  ('King Edward VI Community College', 'Totnes'),
  ('King Edward VI Five Ways School', 'Birmingham'),
  ('King Edward VI Grammar School', 'Louth'),
  ('King Edward VI Grammar School, Chelmsford', 'Chelmsford'),
  ('King Edward VI Handsworth Grammar School for Boys', 'Birmingham'),
  ('King Edward VI Handsworth School', 'Birmingham'),
  ('King Edward VI Handsworth Wood Girls'' Academy', 'Birmingham'),
  ('King Edward VI High School', 'Stafford'),
  ('King Edward VI King''s Norton School for Boys', 'Birmingham'),
  ('King Edward VI Lordswood School for Girls', 'Birmingham'),
  ('King Edward VI Northfield School for Girls', 'Birmingham'),
  ('King Edward VI School', 'Lichfield'),
  ('King Edward VI School', 'Stratford-upon-Avon'),
  ('King Edward VI Sheldon Heath Academy', 'Birmingham'),
  ('King Edward VII Academy', 'King''s Lynn'),
  ('King Edward VII School', 'Sheffield'),
  ('King Ethelbert School', 'Birchington'),
  ('King Harold Business & Enterprise Academy', 'Waltham Abbey'),
  ('King James Academy Royston', 'Royston'),
  ('King James I Academy Bishop Auckland', 'Bishop Auckland'),
  ('King James''s School', 'Knaresborough'),
  ('King James''s School', 'Huddersfield'),
  ('King Solomon High School', 'Ilford'),
  ('King''s Academy Bay House', 'Gosport'),
  ('King''s Academy Binfield', 'Bracknell'),
  ('King''s Academy Brune Park', 'Gosport'),
  ('King''s Academy Easthampstead Park', 'Bracknell'),
  ('King''s Academy Prospect', 'Reading'),
  ('King''s Academy Ringmer', 'Lewes'),
  ('King''s Leadership Academy Bolton', 'Bolton'),
  ('King''s Leadership Academy Hawthornes', 'Bootle'),
  ('King''s Leadership Academy Warrington', 'Warrington'),
  ('King''s Leadership Academy Wavertree', 'Liverpool'),
  ('King''s Leadership Academy, Liverpool', 'Liverpool'),
  ('King''s Lynn Academy', 'King''s Lynn'),
  ('King''s Oak Academy', 'Bristol'),
  ('King''s School', 'Hove'),
  ('Kingdown School', 'Warminster'),
  ('Kings College Guildford', 'Guildford'),
  ('Kings Heath Secondary School', 'Birmingham'),
  ('Kings Interhigh', 'London'),
  ('Kings International College', 'Camberley'),
  ('Kings Langley School', 'Kings Langley'),
  ('Kings Norton Girls'' School', 'Birmingham'),
  ('Kings Priory School', 'North Shields'),
  ('Kings'' School', 'Winchester'),
  ('Kingsbridge Academy', 'Kingsbridge'),
  ('Kingsbury Green Academy', 'Calne'),
  ('Kingsbury High School', 'London'),
  ('Kingsbury School - A Specialist Science and Mathematics Academy', 'Kingsbury'),
  ('Kingsdale Foundation School', 'London'),
  ('Kingsdown School', 'Swindon'),
  ('Kingsford Community School', 'London'),
  ('Kingsmead Academy', 'Taunton'),
  ('Kingsmead School', 'Enfield'),
  ('Kingsmead School', 'Cannock'),
  ('Kingsmeadow Community School', 'Gateshead'),
  ('Kingsthorpe College', 'Northampton'),
  ('Kingstone High School', 'Hereford'),
  ('Kingsway Park High School', 'Rochdale'),
  ('Kingswinford Academy', 'Kingswinford'),
  ('Kingswood Secondary Academy', 'Corby'),
  ('Kinver High School and Sixth Form', 'Stourbridge'),
  ('Kirk Balk Academy', 'Barnsley'),
  ('Kirk Hallam Community Academy', 'Ilkeston'),
  ('Kirkbie Kendal School', 'Kendal'),
  ('Kirkburton Middle School', 'Huddersfield'),
  ('Kirkby High School', 'Liverpool'),
  ('Kirkby Stephen Grammar School', 'Kirkby Stephen'),
  ('Kirton Academy', 'Gainsborough'),
  ('Knole Academy', 'Sevenoaks'),
  ('Knutsford Academy', 'Knutsford'),
  ('La Retraite Roman Catholic Girls'' School', 'London'),
  ('La Sainte Union Catholic Secondary School', 'London'),
  ('Lady Hawkins'' School', 'Kington'),
  ('Lady Lumley''s Academy', 'Pickering'),
  ('Lady Manners School', 'Bakewell'),
  ('Lady Margaret School', 'London'),
  ('Ladybridge High School', 'Bolton'),
  ('Laisterdyke Leadership Academy', 'Bradford'),
  ('Lakelands Academy', 'Ellesmere'),
  ('Lammas School', 'London'),
  ('Lampton Academy', 'Hounslow'),
  ('Lancaster Academy', 'Leicester'),
  ('Lancaster Girls'' Grammar School', 'Lancaster'),
  ('Lancaster High School', 'Lancaster'),
  ('Lancaster Royal Grammar School', 'Lancaster'),
  ('Landau Forte Academy, Amington', 'Tamworth'),
  ('Landau Forte Academy, QEMS', 'Tamworth'),
  ('Landau Forte College', 'Derby'),
  ('Langdon Academy', 'London'),
  ('Langdon Park Community School', 'London'),
  ('Langley Grammar School', 'Langley'),
  ('Langley Park School for Boys', 'Beckenham'),
  ('Langley Park School for Girls', 'Beckenham'),
  ('Langley School', 'Solihull'),
  ('Langtree School', 'Reading'),
  ('Larkmead School', 'Abingdon'),
  ('Lathom High School : A Technology College', 'Skelmersdale'),
  ('Launceston College', 'Launceston'),
  ('Laureate Academy', 'Hemel Hempstead'),
  ('Laurel Park School', 'London'),
  ('Laurence Jackson School', 'Guisborough'),
  ('Laurus Cheadle Hulme', 'Cheadle'),
  ('Laurus Ryecroft', 'Manchester'),
  ('Lavington School', 'Devizes'),
  ('Lawn Manor Academy', 'Swindon'),
  ('Lawnswood School', 'Leeds'),
  ('Lawrence Sheriff School', 'Rugby'),
  ('Lea Manor High School', 'Luton'),
  ('LeAF Studio', 'Bournemouth'),
  ('Lealands High School', 'Luton'),
  ('Leasowes High School', 'Halesowen'),
  ('Leeds City Academy', 'Leeds'),
  ('Leeds East Academy', 'Leeds'),
  ('Leeds Jewish Free School', 'Leeds'),
  ('Leeds West Academy', 'Leeds'),
  ('Leek High School', 'Leek'),
  ('Lees Brook Academy', 'Derby'),
  ('Leigh Academy Bexley', 'Erith'),
  ('Leigh Academy Blackheath', 'London'),
  ('Leigh Academy Ebbsfleet', 'Swanscombe'),
  ('Leigh Academy Halley', 'London'),
  ('Leigh Academy Hugh Christie', 'Tonbridge'),
  ('Leigh Academy Hundred of Hoo', 'Rochester'),
  ('Leigh Academy Longfield', 'Longfield'),
  ('Leigh Academy Mascalls', 'Tonbridge'),
  ('Leigh Academy Minster', 'Sheerness'),
  ('Leigh Academy Rainham', 'Gillingham'),
  ('Leigh Academy Strood', 'Rochester'),
  ('Leigh Academy Tonbridge', 'Tonbridge'),
  ('Leigh Academy Wilmington', 'Wilmington'),
  ('Leigh Stationers'' Academy', 'London'),
  ('Leigh UTC Dartford', 'Dartford'),
  ('Leighton Middle School', 'Leighton Buzzard'),
  ('Levenshulme High School', 'Manchester'),
  ('Leventhorpe', 'Sawbridgeworth'),
  ('Leytonstone School', 'London'),
  ('Liberty Academy', 'Hull'),
  ('Lift Aylward', 'London'),
  ('Lift Beacon High', 'London'),
  ('Lift Bexleyheath', 'Bexleyheath'),
  ('Lift Broadlands', 'Bristol'),
  ('Lift Clacton', 'Clacton on Sea'),
  ('Lift Firth Park', 'Sheffield'),
  ('Lift Four Dwellings Secondary', 'Birmingham'),
  ('Lift Greensward', 'Hockley'),
  ('Lift Greenwood', 'Birmingham'),
  ('Lift Kingsley', 'Hounslow'),
  ('Lift Kingswood', 'Hull')
ON CONFLICT (name, town) DO NOTHING;
