-- Chunk 6 of 7 (500 schools)
INSERT INTO public.schools (name, town) VALUES
  ('St Mary''s Church of England High School (VA)', 'Waltham Cross'),
  ('St Mary''s Church of England Middle School, Puddletown', 'Dorchester'),
  ('St Mary''s College, Voluntary Catholic Academy', 'Hull'),
  ('St Mary''s RC High School', 'Hereford'),
  ('St Matthew Academy', 'London'),
  ('St Matthew''s RC High School', 'Manchester'),
  ('St Matthias School', 'Wolverhampton'),
  ('St Michael''s Catholic Academy', 'Billingham'),
  ('St Michael''s Catholic College', 'London'),
  ('St Michael''s Catholic Grammar School', 'London'),
  ('St Michael''s Catholic School', 'High Wycombe'),
  ('St Michael''s Church of England High School', 'Rowley Regis'),
  ('St Michael''s Church of England High School', 'Chorley'),
  ('St Michael''s Church of England Middle School, Colehill', 'Wimborne'),
  ('St Michaels Church of England Academy', 'Crosby'),
  ('St Monica''s RC High School, a Voluntary Academy', 'Manchester'),
  ('St Nicholas Catholic High School', 'Northwich'),
  ('St Olave''s and St Saviour''s Grammar School', 'Orpington'),
  ('St Oscar Romero Catholic School', 'Worthing'),
  ('St Osmund''s Church of England Middle School', 'Dorchester'),
  ('St Patrick''s Catholic College, A Voluntary Catholic Academy', 'Stockton-on-Tees'),
  ('St Patrick''s RC High School', 'Manchester'),
  ('St Paul''s Academy', 'London'),
  ('St Paul''s Catholic College', 'Burgess Hill'),
  ('St Paul''s Catholic College', 'Sunbury-on-Thames'),
  ('St Paul''s Catholic School', 'Milton Keynes'),
  ('St Paul''s Catholic School, a Voluntary Academy', 'Leicester'),
  ('St Paul''s School for Girls', 'Birmingham'),
  ('St Paul''s Way Trust School', 'London'),
  ('St Peter and St Paul, Catholic Voluntary Academy', 'Lincoln'),
  ('St Peter''s Catholic College', 'Middlesbrough'),
  ('St Peter''s Catholic Comprehensive School', 'Bournemouth'),
  ('St Peter''s Catholic High School', 'Wigan'),
  ('St Peter''s Catholic High School and Sixth Form Centre', 'Gloucester'),
  ('St Peter''s Catholic School', 'Guildford'),
  ('St Peter''s Catholic School', 'Solihull'),
  ('St Peter''s Church of England Aided School', 'Exeter'),
  ('St Peter''s Church of England Middle School', 'Windsor'),
  ('St Peter''s CofE Academy', 'Stoke-on-Trent'),
  ('St Peter''s Collegiate Academy', 'Wolverhampton'),
  ('St Peter''s RC High School', ''),
  ('St Peter''s School', 'Huntingdon'),
  ('St Philip Howard Catholic School', 'Bognor Regis'),
  ('St Philip Howard Catholic Voluntary Academy', 'Glossop'),
  ('St Philomena''s Catholic High School for Girls', 'Carshalton'),
  ('St Regis Church of England Academy', 'Wolverhampton'),
  ('St Richard Reynolds Catholic High School', 'London'),
  ('St Richard''s Catholic College', 'Bexhill-on-Sea'),
  ('St Robert of Newminster Catholic School and Sixth Form College, Washington', 'Washington'),
  ('St Saviour''s and St Olave''s Church of England School', 'London'),
  ('St Simon Stock Catholic School', 'Maidstone'),
  ('St Thomas Aquinas Catholic School', 'Birmingham'),
  ('St Thomas Becket Catholic School', 'Northampton'),
  ('St Thomas More Catholic Academy', 'Stoke-on-Trent'),
  ('St Thomas More Catholic Comprehensive School', 'London'),
  ('St Thomas More Catholic High School', 'North Shields'),
  ('St Thomas More Catholic High School', 'Crewe'),
  ('St Thomas More Catholic School', 'London'),
  ('St Thomas More Catholic School', 'Bedford'),
  ('St Thomas More Catholic School and Sixth Form College', 'Nuneaton'),
  ('St Thomas More Catholic School, Blaydon', 'Blaydon-on-Tyne'),
  ('St Thomas More Catholic School, Willenhall', 'Willenhall'),
  ('St Thomas More Catholic Voluntary Academy', 'Buxton'),
  ('St Thomas More High School', 'Westcliff-on-Sea'),
  ('St Thomas More RC College', 'Manchester'),
  ('St Thomas à Becket Catholic Secondary School, A Voluntary Academy', 'Wakefield'),
  ('St Ursula''s Convent School', 'London'),
  ('St Wilfrid''s Catholic Comprehensive School, Crawley', 'Crawley'),
  ('St Wilfrid''s Catholic High School & Sixth Form College: A Voluntary Academy', 'Pontefract'),
  ('St Wilfrid''s Church of England Academy', 'Blackburn'),
  ('St Wilfrid''s RC College', 'South Shields'),
  ('St. Mary''s Menston, a Catholic Voluntary Academy', 'Ilkley'),
  ('St. Thomas More Language College', 'London'),
  ('Stafford Manor High School', 'Stafford'),
  ('Staffordshire University Academy', 'Cannock'),
  ('Staindrop Academy', 'Darlington'),
  ('Stalham High School', 'Norwich'),
  ('Stamford Welland Academy', 'Stamford'),
  ('Stanborough School', 'Welwyn Garden City'),
  ('Stanchester Academy', 'Stoke-sub-Hamdon'),
  ('Standish Community High School', 'Wigan'),
  ('Stanground Academy', 'Peterborough'),
  ('Stanley High School', 'Southport'),
  ('Stantonbury School', 'Milton Keynes'),
  ('Star King Solomon Academy', 'Birmingham'),
  ('Star Radcliffe Academy', 'Radcliffe'),
  ('Star Salford Academy', 'Worsley'),
  ('Starbank School', 'Birmingham'),
  ('Stepney All Saints Church of England Secondary School', 'London'),
  ('Stewards Academy - Science Specialist, Harlow', 'Harlow'),
  ('Steyning Grammar School', 'Steyning'),
  ('Stockland Green School', 'Birmingham'),
  ('Stockport Academy', 'Stockport'),
  ('Stockport School', 'Stockport'),
  ('Stocksbridge High School', 'Sheffield'),
  ('Stoke Damerel Community College', 'Plymouth'),
  ('Stoke High School - Ormiston Academy', 'Ipswich'),
  ('Stoke Newington School and Sixth Form', 'London'),
  ('Stoke Park School', 'Coventry'),
  ('Stokesley School', 'Stokesley'),
  ('Stone Lodge School', 'Dartford'),
  ('Stopsley High School', 'Luton'),
  ('Stour Valley Community School', 'Sudbury'),
  ('Stowmarket High School', 'Stowmarket'),
  ('Stowupland High School', 'Stowmarket'),
  ('Stradbroke High School', 'Eye'),
  ('Stratford Girls'' Grammar School', 'Stratford-upon-Avon'),
  ('Stratford School Academy', 'London'),
  ('Stratford Upon Avon School', 'Stratford-upon-Avon'),
  ('Stratton School', 'Biggleswade'),
  ('Stretford Grammar School', 'Manchester'),
  ('Stretford High School', 'Manchester'),
  ('Stroud High School', 'Stroud'),
  ('Stuart Bathurst Catholic High School', 'Wednesbury'),
  ('Studio West', 'Newcastle-upon-Tyne'),
  ('Studley High School', 'Studley'),
  ('Sturminster Newton High School', 'Sturminster Newton'),
  ('Summerhill School', 'Kingswinford'),
  ('Sunbury Manor School', 'Sunbury-on-Thames'),
  ('Sutton Coldfield Grammar School for Girls', 'Sutton Coldfield'),
  ('Sutton Community Academy', 'Sutton-in-Ashfield'),
  ('Sutton Grammar School', 'Sutton'),
  ('Swakeleys School for Girls', 'Uxbridge'),
  ('Swanlea School', 'London'),
  ('Swanmore College', 'Southampton'),
  ('Swanshurst School', 'Birmingham'),
  ('Swanwick Hall School', 'Alfreton'),
  ('Swavesey Village College', 'Cambridge'),
  ('Swindon Academy', 'Swindon'),
  ('Swinton Academy', 'Mexborough'),
  ('Sybil Andrews Academy', 'Bury St. Edmunds'),
  ('Sydenham School', 'London'),
  ('Tabor Academy', 'Braintree'),
  ('Tadcaster Grammar School', 'Tadcaster'),
  ('Tanbridge House School', 'Horsham'),
  ('Tanfield School', 'Stanley'),
  ('Tapton School & Sixth Form', 'Sheffield'),
  ('Tarleton Academy', 'Preston'),
  ('Tarporley High School and Sixth Form College', 'Tarporley'),
  ('Tauheedul Islam Boys'' High School', 'Blackburn'),
  ('Tauheedul Islam Girls'' High School', 'Blackburn'),
  ('Taverham High School', 'Norwich'),
  ('Tavistock College', 'Tavistock'),
  ('TCES National Online School', 'Wimbledon'),
  ('Teddington School', 'Teddington'),
  ('Teesdale School and Sixth Form', 'Barnard Castle'),
  ('Teign School', 'Newton Abbot'),
  ('Teignmouth Community School, Exeter Road', 'Teignmouth'),
  ('Temple Learning Academy', 'Leeds'),
  ('Temple Moor High School', 'Leeds'),
  ('Tenbury High Ormiston Academy', 'Tenbury Wells'),
  ('Testbourne Community School', 'Whitchurch'),
  ('Testwood School', 'Southampton'),
  ('Tewkesbury Academy', 'Tewkesbury'),
  ('Thames Park Secondary School', 'Grays'),
  ('Thamesmead School', 'Shepperton'),
  ('Thamesview School', 'Gravesend'),
  ('The Abbey School', 'Faversham'),
  ('The Academy at Shotton Hall', 'Peterlee'),
  ('The Academy of St Francis of Assisi', 'Liverpool'),
  ('The Academy of St Nicholas', 'Liverpool'),
  ('The Academy, Selsey', 'Chichester'),
  ('The Adeyfield Academy', 'Hemel Hempstead'),
  ('The Albion Academy', 'Salford'),
  ('The Angmering School', 'Littlehampton'),
  ('The Appleton School', 'Benfleet'),
  ('The Archbishop Lanfranc Academy', 'Croydon'),
  ('The Archbishop''s School', 'Canterbury'),
  ('The Archer Academy', 'London'),
  ('The Arnewood School', 'New Milton'),
  ('The Arthur Terry School', 'Sutton Coldfield'),
  ('The Ashcombe School', 'Dorking'),
  ('The Astley Cooper School', 'Hemel Hempstead'),
  ('The Avon Valley School and Performing Arts College', 'Rugby'),
  ('The Axholme Academy', 'Crowle'),
  ('The Aylesbury Vale Academy', 'Aylesbury'),
  ('The Banovallum School', 'Horncastle'),
  ('The Barlow RC High School and Specialist Science College', 'Manchester'),
  ('The Barnes Wallis Academy', 'Lincoln'),
  ('The Basildon Lower Academy', 'Basildon'),
  ('The Basildon Upper Academy', 'Basildon'),
  ('The Bay Church of England School', 'Sandown'),
  ('The Beacon School', 'Banstead'),
  ('The Beaconsfield School', 'Beaconsfield'),
  ('The Beaulieu Park School', 'Chelmsford'),
  ('The Becket School', 'West Bridgford'),
  ('The Belvedere Academy', 'Liverpool'),
  ('The Bemrose School', 'Derby'),
  ('The Bewdley School', 'Bewdley'),
  ('The Bicester School', 'Bicester'),
  ('The Billericay School', 'Billericay'),
  ('The Birley Academy', 'Sheffield'),
  ('The Bishop David Brown School', 'Woking'),
  ('The Bishop of Hereford''s Bluecoat School', 'Hereford'),
  ('The Bishop of Winchester Academy', 'Bournemouth'),
  ('The Bishop Wand Church of England School', 'Sunbury-on-Thames'),
  ('The Bishop''s Stortford High School', 'Bishop''s Stortford'),
  ('The Bishops'' Blue Coat Church of England High School', 'Chester'),
  ('The Blandford School', 'Blandford Forum'),
  ('The Blue Coat CofE School', 'Oldham'),
  ('The Blue Coat School', 'Liverpool'),
  ('The Blue Coat School Basingstoke', 'Basingstoke'),
  ('The Blue School', 'Wells'),
  ('The Blyth Academy', 'Blyth'),
  ('The Bolsover School', 'Chesterfield'),
  ('The Boston Grammar School', 'Boston'),
  ('The Boswells School', 'Chelmsford'),
  ('The Boulevard Academy', 'Kingston-upon-Hull'),
  ('The Bourne Academy', 'Bournemouth'),
  ('The Brakenhale School', 'Bracknell'),
  ('The Brian Clarke Church of England Academy', 'Oldham'),
  ('The Bridge Academy', 'London'),
  ('The Brittons Academy', 'Rainham'),
  ('The Bromfords School', 'Wickford'),
  ('The Brooksbank School', 'Elland'),
  ('The Broxbourne School', 'Broxbourne'),
  ('The Brunts Academy', 'Mansfield'),
  ('The Bulmershe School', 'Reading'),
  ('The Bulwell Academy', 'Nottingham'),
  ('The Burgate School and Sixth Form', 'Fordingbridge'),
  ('The Burgess Hill Academy', 'Burgess Hill'),
  ('The Burton Borough School', 'Newport'),
  ('The Byrchall High School', 'Wigan'),
  ('The Calder Learning Trust', 'Hebden Bridge'),
  ('The Camden School for Girls', 'London'),
  ('The Campion School', 'Hornchurch'),
  ('The Canterbury Academy', 'Canterbury'),
  ('The Cardinal Vaughan Memorial RC School', 'London'),
  ('The Cardinal Wiseman Catholic School', 'Greenford'),
  ('The Castle Rock School', 'Coalville'),
  ('The Castle School', 'Taunton'),
  ('The Castle School', 'Bristol'),
  ('The Catholic High School, Chester', 'Chester'),
  ('The Cavendish School', 'Eastbourne'),
  ('The Cedars Academy', 'Leicester'),
  ('The Chalfonts Community College', 'Gerrards Cross'),
  ('The Chalk Hills Academy', 'Luton'),
  ('The Chantry School', 'Worcester'),
  ('The Charles Dickens School', 'Broadstairs'),
  ('The Charter School Bermondsey', 'London'),
  ('The Charter School East Dulwich', 'London'),
  ('The Charter School North Dulwich', 'London'),
  ('The Chase', 'Malvern'),
  ('The Chauncy School', 'Ware'),
  ('The Cheadle Academy', 'Stoke-on-Trent'),
  ('The Cherwell School', 'Oxford'),
  ('The City Academy Bristol', 'Bristol'),
  ('The City Academy, Hackney', 'London'),
  ('The City of Leicester College', 'Leicester'),
  ('The Clarendon Academy', 'Trowbridge'),
  ('The Clere School', 'Newbury'),
  ('The Coleshill School', 'Birmingham'),
  ('The Commonweal School', 'Swindon'),
  ('The Community College, Bishop''s Castle', 'Bishops Castle'),
  ('The Compton School', 'London'),
  ('The Cooper School', 'Bicester'),
  ('The Coopers'' Company and Coborn School', 'Upminster'),
  ('The Corbet School', 'Shrewsbury'),
  ('The Cornelius Vermuyden School', 'Canvey Island'),
  ('The Cornerstone Academy', 'Poole'),
  ('The Corsham School', 'Corsham'),
  ('The Costello School', 'Basingstoke'),
  ('The Cotswold Academy', 'Cheltenham'),
  ('The Cottesloe School', 'Aylesbury'),
  ('The County High School, Leftwich', 'Northwich'),
  ('The Cowplain School', 'Waterlooville'),
  ('The Crestwood School', 'Dudley'),
  ('The Crompton House Church of England Academy', 'Oldham'),
  ('The Crossley Heath School', 'Halifax'),
  ('The Crypt School', 'Gloucester'),
  ('The de Ferrers Academy', 'Burton-on-Trent'),
  ('The De Montfort School', 'Evesham'),
  ('The Dean Academy', 'Lydney'),
  ('The Deanery Church of England High School and Sixth Form College', 'Wigan'),
  ('The Deanery CofE Academy', 'Swindon'),
  ('The Deanes', 'Benfleet'),
  ('The Deepings School', 'Peterborough'),
  ('The Derby High School', 'Lancs'),
  ('The Dorcan Academy', 'Swindon'),
  ('The Dormston School', 'Dudley'),
  ('The Douay Martyrs Catholic School', 'Uxbridge'),
  ('The Downs School', 'Newbury'),
  ('The Duchess''s Community High School', 'Alnwick'),
  ('The Dukeries Academy', 'Newark'),
  ('The Duston School', 'Northampton'),
  ('The Earls High School', 'Halesowen'),
  ('The East Manchester Academy', 'Manchester'),
  ('The Eastbourne Academy', 'Eastbourne'),
  ('The Eastwood Academy', 'Leigh-on-Sea'),
  ('The Ecclesbourne School', 'Belper'),
  ('The Elizabethan Academy', 'Retford'),
  ('The Ellen Wilkinson School for Girls', 'London'),
  ('The Elmgreen School', 'London'),
  ('The Elms Academy', 'London'),
  ('The Elton High School', 'Bury'),
  ('The Emmbrook School', 'Wokingham'),
  ('The Excel Academy', 'Stoke-on-Trent'),
  ('The Excelsior Academy', 'London'),
  ('The Fallibroome Academy', 'Macclesfield'),
  ('The Farnley Academy', 'Leeds'),
  ('The Featherstone Academy', 'Pontefract'),
  ('The Ferrers School', 'Rushden'),
  ('The FitzWimarc School', 'Rayleigh'),
  ('The Five Islands Academy', 'St Mary''s'),
  ('The Folkestone School for Girls', 'Folkestone'),
  ('The Forest School', 'Wokingham'),
  ('The Forest School', 'Horsham'),
  ('The Frances Bardsley Academy for Girls', 'Romford'),
  ('The Friary School', 'Lichfield'),
  ('The Fulham Boys School', 'London'),
  ('The Gainsborough Academy', 'Gainsborough'),
  ('The Garibaldi School', 'Mansfield'),
  ('The Gateway Academy', 'Grays'),
  ('The Gatwick School', 'Crawley'),
  ('The Gilberd School', 'Colchester'),
  ('The Giles Academy', 'Boston'),
  ('The Grange Academy', 'Bushey'),
  ('The Grange School', 'Aylesbury'),
  ('The Grange School', 'Christchurch'),
  ('The Grange School', 'Runcorn'),
  ('The Grangefield Academy', 'Stockton-on-Tees'),
  ('The Green School for Boys', 'Isleworth'),
  ('The Green School for Girls', 'Isleworth'),
  ('The Grey Coat Hospital', 'London'),
  ('The Grove School', 'Market Drayton'),
  ('The Gryphon School', 'Sherborne'),
  ('The Halifax Academy', 'Halifax'),
  ('The Hamble School', 'Southampton'),
  ('The Harleston Sancroft Academy (a 3-16 Church of England School)', 'Harleston'),
  ('The Hart School', 'Rugeley'),
  ('The Harvey Grammar School', 'Folkestone'),
  ('The Hastings Academy', 'Hastings'),
  ('The Hathaway Academy', 'Grays'),
  ('The Hathershaw College', 'Oldham'),
  ('The Hayfield School', 'Doncaster'),
  ('The Hayling College', 'Hayling Island'),
  ('The Hazeley Academy', 'Milton Keynes'),
  ('The Heath School', 'Runcorn'),
  ('The Heathland School', 'Hounslow'),
  ('The Hemel Hempstead School', 'Hemel Hempstead'),
  ('The Henrietta Barnett School', 'London'),
  ('The Henry Box School', 'Witney'),
  ('The Henry Cort Community College', 'Fareham'),
  ('The Hereford Church of England Academy', 'Hereford'),
  ('The Herewoode Academy', 'Leicester'),
  ('The Hertfordshire & Essex High School and Science College', 'Bishop''s Stortford'),
  ('The Heys School', 'Manchester'),
  ('The High School Leckhampton', 'Cheltenham'),
  ('The Highcrest Academy', 'High Wycombe'),
  ('The Highfield School', 'Letchworth Garden City'),
  ('The Hinckley School', 'Hinckley'),
  ('The Holgate Academy', 'Nottingham'),
  ('The Hollins', 'Accrington'),
  ('The Hollyfield School and Sixth Form Centre', 'Surbiton'),
  ('The Holmesdale School', 'Snodland'),
  ('The Holt School', 'Wokingham'),
  ('The Holy Cross School', 'New Malden'),
  ('The Holy Family Catholic School, a Voluntary Academy', 'Keighley'),
  ('The Howard School', 'Gillingham'),
  ('The Hurlingham Academy', 'London'),
  ('The Hurst School', 'Tadley'),
  ('The Hyndburn Academy', 'Blackburn'),
  ('The Ilfracombe Church of England Academy', 'Ilfracombe'),
  ('The Island Free School', 'Ventnor'),
  ('The James Hornsby School', 'Basildon'),
  ('The JCB Academy', 'Rocester'),
  ('The John Fisher School', 'Purley'),
  ('The John of Gaunt School', 'Trowbridge'),
  ('The John Roan School', 'London'),
  ('The John Wallis Church of England Academy', 'Ashford'),
  ('The John Warner School', 'Hoddesdon'),
  ('The Joseph Whitaker School', 'Mansfield'),
  ('The Judd School', 'Tonbridge'),
  ('The Khalsa Academy Wolverhampton', 'Wolverhampton'),
  ('The Kimberley School', 'Nottingham'),
  ('The King Alfred School an Academy', 'Highbridge'),
  ('The King David High School', 'Manchester'),
  ('The King Edmund School', 'Rochford'),
  ('The King Edward VI School', 'Morpeth'),
  ('The King John School', 'Benfleet'),
  ('The King''s (The Cathedral) School', 'Peterborough'),
  ('The King''s Academy', 'Middlesbrough'),
  ('The King''s CofE Academy', 'Stoke-on-Trent'),
  ('The King''s School', 'Ottery St Mary'),
  ('The King''s School', 'Pontefract'),
  ('The King''s School, Grantham', 'Grantham'),
  ('The Kings of Wessex Academy', 'Cheddar'),
  ('The Kingsbrook School', 'Aylesbury'),
  ('The Kingston Academy', 'Kingston upon Thames'),
  ('The Kingsway School', 'Cheadle'),
  ('The Knights Templar School', 'Baldock'),
  ('The Lacon Childe School', 'Kidderminster'),
  ('The Lakes School', 'Windermere'),
  ('The Langley Academy', 'Slough'),
  ('The Latimer Arts College', 'Kettering'),
  ('The Latymer School', 'London'),
  ('The Laurel Academy', 'Mexborough'),
  ('The Lea Valley Academy', 'Enfield'),
  ('The Lenham School', 'Maidstone'),
  ('The Link Academy', 'Dudley'),
  ('The Littlehampton Academy', 'Littlehampton'),
  ('The London Oratory School', 'London'),
  ('The Long Eaton School', 'Nottingham'),
  ('The Lowry Academy', 'Manchester'),
  ('The Macclesfield Academy', 'Macclesfield'),
  ('The Magna Carta School', 'Staines-upon-Thames'),
  ('The Malling School', 'West Malling'),
  ('The Mandeville School', 'Aylesbury'),
  ('The Manor Academy', 'Mansfield'),
  ('The Maplesden Noakes School', 'Maidstone'),
  ('The Marches School', 'Oswestry'),
  ('The Market Bosworth School', 'Nuneaton'),
  ('The Market Weighton School', 'Market Weighton'),
  ('The Marlborough Church of England School', 'Woodstock'),
  ('The Marlborough Science Academy', 'St Albans'),
  ('The Marsh Academy', 'New Romney'),
  ('The Martin High School Anstey', 'Leicester'),
  ('The Marvell College', 'Hull'),
  ('The Matthew Arnold School', 'Staines-upon-Thames'),
  ('The McAuley Catholic High School', 'Doncaster'),
  ('The Milton Keynes Academy', 'Milton Keynes'),
  ('The Minster School', 'Southwell'),
  ('The Mirfield Free Grammar', 'Mirfield'),
  ('The Misbourne School', 'Great Missenden'),
  ('The Morley Academy', 'Leeds'),
  ('The Mosslands School', 'Wallasey'),
  ('The Mountbatten School', 'Romsey'),
  ('The National CofE Academy', 'Nottingham'),
  ('The Nelson Thomlinson School', 'Wigton'),
  ('The Netherhall School', 'Cambridge'),
  ('The Newark Academy', 'Newark'),
  ('The Newbridge School', 'Coalville'),
  ('The Nicholas Hamond Academy', 'Swaffham'),
  ('The Nobel School', 'Stevenage'),
  ('The North Halifax Grammar School', 'Halifax'),
  ('The North School', 'Ashford'),
  ('The Norton Knatchbull School', 'Ashford'),
  ('The Norwood School', 'London'),
  ('The Nottingham Emmanuel School', 'West Bridgford'),
  ('The Oaks Academy', 'Crewe'),
  ('The Oakwood Academy', 'Nottingham'),
  ('The Oldershaw School', 'Wallasey'),
  ('The Ongar Academy', 'Ongar'),
  ('The Open Academy', 'Norwich'),
  ('The Orme Academy', 'Newcastle'),
  ('The Oxford Academy', 'Oxford'),
  ('The Palmer Catholic Academy', 'Ilford'),
  ('The Park Community School', 'Barnstaple'),
  ('The Parker E-ACT Academy', 'Daventry'),
  ('The Pedmore High School', 'Stourbridge'),
  ('The Petersfield School', 'Petersfield'),
  ('The Phoenix Collegiate', 'West Bromwich'),
  ('The Piggott School', 'Reading'),
  ('The Pingle Academy', 'Swadlincote'),
  ('The Polesworth School', 'Tamworth'),
  ('The Portsmouth Academy', 'Portsmouth'),
  ('The Prescot School', 'Liverpool'),
  ('The Priory Academy LSST', 'Lincoln'),
  ('The Priory Belvoir Academy', 'Nottingham'),
  ('The Priory Church of England School', 'Dorking'),
  ('The Priory City of Lincoln Academy', 'Lincoln'),
  ('The Priory Pembroke Academy', 'Lincoln'),
  ('The Priory Ruskin Academy', 'Grantham'),
  ('The Priory School', 'Hitchin'),
  ('The Priory School', 'Shrewsbury'),
  ('The Priory Witham Academy', 'Lincoln'),
  ('The Purbeck School', 'Wareham'),
  ('The Queen Elizabeth Academy', 'Atherstone'),
  ('The Queen Elizabeth''s High School, Gainsborough', 'Gainsborough'),
  ('The Queen Katherine School', 'Kendal'),
  ('The Quest Academy', 'South Croydon'),
  ('The Radcliffe School', 'Milton Keynes'),
  ('The Radclyffe School', 'Oldham'),
  ('The Ramsey Academy, Halstead', 'Halstead'),
  ('The Ravensbourne School', 'Bromley'),
  ('The Reach Free School', 'Rickmansworth'),
  ('The Regis School', 'West Sussex'),
  ('The Richmond upon Thames School', 'Twickenham'),
  ('The Ridgeway School & Sixth Form College', 'Swindon'),
  ('The Ripley Academy', 'Ripley'),
  ('The Robert Napier School', 'Gillingham'),
  ('The Robert Smyth Academy', 'Market Harborough'),
  ('The Rochester Grammar School', 'Rochester'),
  ('The Romsey School', 'Romsey'),
  ('The Roseland Academy', 'Truro'),
  ('The Roundhill Academy', 'Leicester'),
  ('The Royal Grammar School, High Wycombe', 'High Wycombe'),
  ('The Royal Harbour Academy', 'Ramsgate'),
  ('The Royal Liberty School', 'Romford'),
  ('The Royal School, Wolverhampton', 'Wolverhampton'),
  ('The Royal Sutton School', 'Sutton Coldfield'),
  ('The Rudheath Senior Academy', 'Northwich'),
  ('The Rural Enterprise Academy', 'Penkridge'),
  ('The Ruth Gorse Academy', 'Leeds'),
  ('The Sacred Heart Language College', 'Harrow'),
  ('The Saint John Henry Newman Catholic School', 'Stevenage'),
  ('The Salesian Academy of St John Bosco', 'Bootle'),
  ('The Sandon School', 'Chelmsford'),
  ('The Sele School', 'Hertford'),
  ('The Sir John Colfox Academy', 'Bridport')
ON CONFLICT (name, town) DO NOTHING;
