-- Chunk 1 of 7 (500 schools)
INSERT INTO public.schools (name, town) VALUES
  ('Abbey College, Ramsey', 'Ramsey'),
  ('Abbey Grange Church of England Academy', 'Leeds'),
  ('Abbey Park School', 'Swindon'),
  ('Abbeyfield School', 'Northampton'),
  ('Abbeyfield School', 'Chippenham'),
  ('Abbeywood Community School', 'Bristol'),
  ('Abbot Beyne School', 'Burton-on-Trent'),
  ('Abbs Cross Academy and Arts College', 'Hornchurch'),
  ('Abraham Moss Community School', 'Manchester'),
  ('Academy 360', 'Sunderland'),
  ('Academy21', 'London'),
  ('Academy@Worden', 'Leyland'),
  ('Accrington Academy', 'Accrington'),
  ('Accrington St Christopher''s Church of England High School', 'Accrington'),
  ('Acklam Grange School', 'Middlesbrough'),
  ('Acland Burghley School', 'London'),
  ('Acle Academy', 'Norwich'),
  ('Ada Lovelace Church of England High School', 'London'),
  ('Addey and Stanhope School', 'London'),
  ('Admiral Lord Nelson School', 'Portsmouth'),
  ('AIM Academy North London', 'London'),
  ('Airedale Academy', 'Castleford'),
  ('Alameda Middle School', 'Bedford'),
  ('Albany Academy', 'Chorley'),
  ('Alcester Academy', 'Alcester'),
  ('Alcester Grammar School', 'Alcester'),
  ('Alde Valley Academy', 'Leiston'),
  ('Alder Community High School', 'Hyde'),
  ('Alder Grange School', 'Rossendale'),
  ('Alderbrook School', 'Solihull'),
  ('Aldercar High School', 'Nottingham'),
  ('Alderman Peel High School', 'Wells-next-the-Sea'),
  ('Alderman White School', 'Nottingham'),
  ('Aldersley High School', 'Wolverhampton'),
  ('Alderwood School', 'Aldershot'),
  ('Aldridge School - A Science College', 'Walsall'),
  ('AldridgeUTC@MediaCityUK', 'Salford'),
  ('Alec Hunter Academy', 'Braintree'),
  ('Alec Reed Academy', 'Northolt'),
  ('Alexandra Park School', 'London'),
  ('Alkerden Church of England Academy', 'Ebbsfleet Valley'),
  ('All Hallows Catholic College', 'Macclesfield'),
  ('All Hallows Catholic High School', 'Preston'),
  ('All Hallows Catholic School', 'Farnham'),
  ('All Hallows RC High School', 'Salford'),
  ('All Saints Academy Dunstable', 'Dunstable'),
  ('All Saints Catholic College', 'London'),
  ('All Saints Catholic College', 'Huddersfield'),
  ('All Saints Catholic College', 'Dukinfield'),
  ('All Saints Catholic High School', 'London'),
  ('All Saints Catholic High School', 'Knowsley'),
  ('All Saints Catholic School and Technology College', 'Dagenham'),
  ('All Saints Catholic School York', 'York'),
  ('All Saints Church of England Academy', 'Plymouth'),
  ('All Saints Church of England Academy', 'Stockton-on-Tees'),
  ('All Saints'' Academy, Cheltenham', 'Cheltenham'),
  ('All Saints'' Catholic High School', 'Sheffield'),
  ('All Saints'' Catholic Voluntary Academy', 'Mansfield'),
  ('All Saints'' Church of England Academy', 'Weymouth'),
  ('All Saints'' Roman Catholic High School, a Voluntary Academy', 'Rossendale'),
  ('Allenbourn Middle School', 'Wimborne'),
  ('Allerton Grange School', 'Leeds'),
  ('Allerton High School', 'Leeds'),
  ('Allestree Woodlands School', 'Derby'),
  ('Alleyne''s Academy', 'Stone'),
  ('Alperton Community School', 'Wembley'),
  ('Alsager School', 'Stoke-on-Trent'),
  ('Alsop High School', 'Liverpool'),
  ('Altrincham College', 'Altrincham'),
  ('Altrincham Grammar School for Boys', 'Altrincham'),
  ('Altrincham Grammar School for Girls', 'Altrincham'),
  ('Altwood Church of England School', 'Maidenhead'),
  ('Alvaston Moor Academy', 'Derby'),
  ('Alvechurch CofE Middle School', 'Birmingham'),
  ('Amersham School', 'Amersham'),
  ('Amery Hill School', 'Alton'),
  ('Anglo European School', 'Ingatestone'),
  ('Ansford Academy', 'Castle Cary'),
  ('Anthony Gell School', 'Matlock'),
  ('Appleby Grammar School', 'Appleby-in-Westmorland'),
  ('Applemore College', 'Southampton'),
  ('Appleton Academy', 'Bradford'),
  ('Archbishop Beck Catholic College', 'Liverpool'),
  ('Archbishop Blanch CofE High School', 'Liverpool'),
  ('Archbishop Holgate''s School, A Church of England Academy', 'York'),
  ('Archbishop Ilsley Catholic School', 'Birmingham'),
  ('Archbishop Temple Church of England High School', 'Preston'),
  ('Archbishop Tenison''s CofE High School', 'Croydon'),
  ('Archway School', 'Stroud'),
  ('Arden', 'Solihull'),
  ('Arena Academy', 'Birmingham'),
  ('Ark Academy', 'Wembley'),
  ('Ark Acton Academy', 'London'),
  ('Ark Alexandra Academy', 'HASTINGS'),
  ('Ark All Saints Academy', 'London'),
  ('Ark Blake Academy', 'Croydon'),
  ('Ark Bolingbroke Academy', 'London'),
  ('Ark Boulton Academy', 'Birmingham'),
  ('Ark Burlington Danes Academy', 'London'),
  ('Ark Charter Academy', 'Southsea'),
  ('Ark Elvin Academy', 'London'),
  ('Ark Evelyn Grace Academy', 'London'),
  ('Ark Globe Academy', 'London'),
  ('Ark Greenwich Free School', 'London'),
  ('Ark Isaac Newton Academy', 'Ilford'),
  ('Ark John Keats Academy', 'London'),
  ('Ark King Solomon Academy', 'London'),
  ('Ark Kings Academy', 'Birmingham'),
  ('Ark Pioneer Academy', 'Barnet'),
  ('Ark Putney Academy', 'London'),
  ('Ark Soane Academy', 'London'),
  ('Ark St Alban''s Academy', 'Birmingham'),
  ('Ark Victoria Academy', 'Birmingham'),
  ('Ark Walworth Academy', 'London'),
  ('Armfield Academy', 'Blackpool'),
  ('Armthorpe Academy', 'Doncaster'),
  ('Arnold Academy', 'Bedford'),
  ('Arnold Hill Spencer Academy', 'Nottingham'),
  ('Arrow Vale High School', 'Redditch'),
  ('Arthur Mellows Village College', 'Peterborough'),
  ('Arts and Media School Islington', 'London'),
  ('Ash Green School', 'Coventry'),
  ('Ash Hill Academy', 'DONCASTER'),
  ('Ash Manor School', 'Ash'),
  ('Ashby School', 'Ashby-De-La-Zouch'),
  ('Ashcroft Technology Academy', 'London'),
  ('Ashfield Comprehensive School', 'Nottingham'),
  ('Ashington Academy', 'Ashington'),
  ('Ashlawn School', 'Rugby'),
  ('Ashlyns School', 'Berkhamsted'),
  ('Ashmole Academy', 'London'),
  ('Ashton Community Science College', 'Preston'),
  ('Ashton Park School', 'Bristol'),
  ('Ashton-on-Mersey School', 'Sale'),
  ('Aston Academy', 'Sheffield'),
  ('Aston Fields Middle School', 'Bromsgrove'),
  ('Aston Manor Academy', 'Birmingham'),
  ('Aston University Engineering Academy', 'Birmingham'),
  ('Astor Secondary School', 'Dover'),
  ('Astrea Academy Dearne', 'Rotherham'),
  ('Astrea Academy Sheffield', 'Sheffield'),
  ('Astrea Academy Woodfields', 'Doncaster'),
  ('Atam Academy', 'Romford'),
  ('Atherton High School', 'Atherton'),
  ('Atlantic Academy', 'Bideford'),
  ('Atlantic Academy Portland', 'Portland'),
  ('Attleborough Academy', 'Attleborough'),
  ('Audenshaw School', 'Manchester'),
  ('Aureus School', 'Didcot'),
  ('Avanti Fields School', 'Leicester'),
  ('Avanti Grange Secondary School', 'Bishops Stortford'),
  ('Avanti House School', 'Stanmore'),
  ('Avon Valley Academy', 'Salisbury'),
  ('Avonbourne Boys'' Academy', 'Bournemouth'),
  ('Avonbourne Girls Academy', 'Bournemouth'),
  ('Axe Valley Academy', 'Axminster'),
  ('Aylesbury Grammar School', 'Aylesbury'),
  ('Aylesbury High School', 'Aylesbury'),
  ('Aylesbury UTC', 'Aylesbury'),
  ('Aylesford School', 'Aylesford'),
  ('Aylesford School Warwick', 'Warwick'),
  ('Aylestone School', 'Hereford'),
  ('Aylsham High School', 'Norwich'),
  ('Babington Academy', 'Leicester'),
  ('Backwell School', 'Bristol'),
  ('Bacon''s College', 'London'),
  ('Bacup and Rawtenstall Grammar School', 'Rossendale'),
  ('Baines School', 'Poulton-le-Fylde'),
  ('Balcarras School', 'Cheltenham'),
  ('Balshaw''s Church of England High School', 'Leyland'),
  ('Barclay Academy', 'Stevenage'),
  ('Barking Abbey School, A Specialist Sports and Humanities College', 'Barking'),
  ('Barlby High School', 'Selby'),
  ('Barnhill Community High School', 'Hayes'),
  ('Barnsley Academy', 'Barnsley'),
  ('Barnwell School', 'Stevenage'),
  ('Barnwood Park School', 'Gloucester'),
  ('Barr Beacon School', 'Walsall'),
  ('Barr''s Hill School', 'Coventry'),
  ('Bartholomew School', 'Witney'),
  ('Bartley Green School', 'Birmingham'),
  ('Barton Court Grammar School', 'Canterbury'),
  ('Barton Manor School', 'Canterbury'),
  ('Bassingbourn Village College', 'Royston'),
  ('Batley Girls'' High School', 'Batley'),
  ('Batley Grammar School', 'Batley'),
  ('Baxter College', 'Kidderminster'),
  ('Bay Leadership Academy', 'Morecambe'),
  ('Baylis Court School', 'Slough'),
  ('Baysgarth School', 'Barton-upon-Humber'),
  ('BBG Academy', 'Birkenshaw'),
  ('Beacon Academy', 'Crowborough'),
  ('Beacon Academy', 'Cleethorpes'),
  ('Beacon Hill Academy', 'Dudley'),
  ('Beacon Hill Community School', 'Wigton'),
  ('Beaconsfield High School', 'Beaconsfield'),
  ('Beal High School', 'Ilford'),
  ('Beaminster School', 'Beaminster'),
  ('Beamont Collegiate Academy', 'Warrington'),
  ('Beauchamp College', 'Leicester'),
  ('Beauchamps High School', 'Wickford'),
  ('Beaumont Leys School', 'Leicester'),
  ('Beaumont School', 'St Albans'),
  ('Beccles High School', 'Beccles'),
  ('Becket Keys Church of England Free School', 'Brentwood'),
  ('Beckfoot Oakbank', 'Keighley'),
  ('Beckfoot School', 'Bingley'),
  ('Beckfoot Thornton', 'Bradford'),
  ('Beckfoot Upper Heaton', 'Bradford'),
  ('Bedale High School', 'Bedale'),
  ('Bede Academy', 'Blyth'),
  ('Bedford Academy', 'Bedford'),
  ('Bedford Free School', 'Bedford'),
  ('Bedford High School', 'Leigh'),
  ('Bedlington Academy', 'Bedlington'),
  ('Bedminster Down School', 'Bristol'),
  ('Beechen Cliff School', 'Bath'),
  ('Beechwood School', 'Slough'),
  ('Beis Yaakov High School', 'Salford'),
  ('Belfairs Academy', 'Leigh-on-Sea'),
  ('Belle Vue Girls'' Academy', 'Bradford'),
  ('Bellerive FCJ Catholic College', 'Liverpool'),
  ('Bellingham Middle School and Sports College', 'Hexham'),
  ('Belmont Community School', 'Durham'),
  ('Belper School and Sixth Form Centre', 'Belper'),
  ('Belvidere School', 'Shrewsbury'),
  ('Benfield School', 'Newcastle-upon-Tyne'),
  ('Benjamin Britten Academy of Music and Mathematics', 'Lowestoft'),
  ('Bennett Memorial Diocesan School', 'Tunbridge Wells'),
  ('Bentley Wood High School', 'Stanmore'),
  ('Benton Park School', 'Leeds'),
  ('Berwick Academy', 'Berwick-upon-Tweed'),
  ('Berwick Middle School', 'Berwick-upon-Tweed'),
  ('Beths Grammar School', 'Bexley'),
  ('Beverley Grammar School', 'Beverley'),
  ('Beverley High School', 'Beverley'),
  ('Bexhill High Academy', 'Bexhill-on-Sea'),
  ('Bexley Grammar School', 'Welling'),
  ('Biddenham International School and Sports College', 'Bedford'),
  ('Biddick Academy', 'Washington'),
  ('Biddulph High School', 'Stoke-on-Trent'),
  ('Bideford College', 'Bideford'),
  ('Bilbrook CofE (VC) Middle School', 'Wolverhampton'),
  ('Bilton School', 'Rugby'),
  ('Bingley Grammar School', 'Bingley'),
  ('Birchensale Middle School', 'Redditch'),
  ('Birches Head Academy', 'Stoke-on-Trent'),
  ('Birchwood Community High School', 'Warrington'),
  ('Birchwood High School', 'Bishop''s Stortford'),
  ('Birkdale High School', 'Southport'),
  ('Birkenhead High School Academy', 'Prenton'),
  ('Birkenhead Park School', 'Birkenhead'),
  ('Birmingham Ormiston Academy', 'Birmingham'),
  ('Bishop Barrington Academy', 'Bishop Auckland'),
  ('Bishop Challoner Catholic College', 'Birmingham'),
  ('Bishop Challoner Catholic School', 'London'),
  ('Bishop Challoner Catholic Secondary School', 'Basingstoke'),
  ('Bishop Douglass School Finchley', 'London'),
  ('Bishop Fox''s School', 'Taunton'),
  ('Bishop Heber High School', 'Malpas'),
  ('Bishop Justus CofE School', 'Bromley'),
  ('Bishop Luffa School, Chichester', 'Chichester'),
  ('Bishop Milner Catholic College', 'Dudley'),
  ('Bishop Perowne CofE College', 'Worcester'),
  ('Bishop Ramsey Church of England School', 'Ruislip'),
  ('Bishop Rawstorne Church of England Academy', 'Leyland'),
  ('Bishop Stopford School', 'Kettering'),
  ('Bishop Stopford''s School', 'Enfield'),
  ('Bishop Thomas Grant Catholic Secondary School', 'London'),
  ('Bishop Ullathorne Catholic School', 'Coventry'),
  ('Bishop Vesey''s Grammar School', 'Sutton Coldfield'),
  ('Bishop Walsh Catholic School', 'Sutton Coldfield'),
  ('Bishop Wordsworth''s Church of England Grammar School', 'Salisbury'),
  ('Bishop Young Church of England Academy', 'Leeds'),
  ('Bishop''s Hatfield Girls'' School', 'Hatfield'),
  ('Bishopshalt School', 'Uxbridge'),
  ('Bitterne Park School', 'Southampton'),
  ('Blackburn Central High School', 'Blackburn'),
  ('Blackfen School for Girls', 'Sidcup'),
  ('Blackminster Middle School', 'Evesham'),
  ('Blackpool Aspire Academy', 'Blackpool'),
  ('Blacon High School, A Specialist Sports College', 'Chester'),
  ('Blaise High School', 'Bristol'),
  ('Blatchington Mill School', 'Hove'),
  ('Blenheim High School', 'Epsom'),
  ('Blessed Carlo Acutis Catholic and Church of England Academy', 'Runcorn'),
  ('Blessed Edward Oldcorne Catholic College', 'Worcester'),
  ('Blessed George Napier Catholic School and Sixth Form', 'Banbury'),
  ('Blessed Hugh Faringdon Catholic School', 'Reading'),
  ('Blessed Robert Sutton Catholic Voluntary Academy', 'Burton-on-Trent'),
  ('Blessed Thomas Holford Catholic College', 'Altrincham'),
  ('Blessed Trinity Roman Catholic College, A Voluntary Academy', 'Burnley'),
  ('Blessed William Howard Catholic School', 'Stafford'),
  ('Bloxwich Academy', 'Walsall'),
  ('Blue Coat Church of England Academy', 'Walsall'),
  ('Blue Coat Church of England School and Music College', 'Coventry'),
  ('Bluecoat Aspley Academy', 'Nottingham'),
  ('Bluecoat Beechdale Academy', 'Nottingham'),
  ('Bluecoat Trent Academy', 'Nottingham'),
  ('Bluecoat Wollaton Academy', 'Nottingham'),
  ('Blythe Bridge High School', 'Stoke-on-Trent'),
  ('Bmat Stem Academy', 'Harlow'),
  ('BOA Digital Technologies Academy', 'Birmingham'),
  ('Bobby Moore Academy', 'London'),
  ('Bodmin College', 'Bodmin'),
  ('Bohunt Farnborough', 'Farnborough'),
  ('Bohunt Horsham', 'Horsham'),
  ('Bohunt School', 'Liphook'),
  ('Bohunt School Wokingham', 'Wokingham'),
  ('Bohunt School Worthing', 'Worthing'),
  ('Bolder Academy', 'Isleworth'),
  ('Boldon School', 'Boldon Colliery'),
  ('Bolton Muslim Girls School', 'Bolton'),
  ('Bolton St Catherine''s Academy', 'Bolton'),
  ('Bonus Pastor Catholic College', 'Bromley'),
  ('Borden Grammar School', 'Sittingbourne'),
  ('Bordesley Green Girls'' School & Sixth Form', 'Birmingham'),
  ('Boroughbridge High School', 'York'),
  ('Boston High School', 'Boston'),
  ('Boston Spa Academy', 'Wetherby'),
  ('Bosworth Academy', 'Leicester'),
  ('Bottisham Village College', 'Cambridge'),
  ('Bourne Academy', 'Bourne'),
  ('Bourne Community College', 'Emsworth'),
  ('Bourne Grammar School', 'Bourne'),
  ('Bournemouth School', 'Bournemouth'),
  ('Bournemouth School for Girls', 'Bournemouth'),
  ('Bournville School', 'Birmingham'),
  ('Bow School', 'London'),
  ('Bower Park Academy', 'Romford'),
  ('Bowland High', 'Clitheroe'),
  ('Bradfield Secondary School', 'Sheffield'),
  ('Bradford Academy', 'Bradford'),
  ('Bradford Forster Academy', 'Bradford'),
  ('Bradford Girls'' Grammar School', 'Bradford'),
  ('Bradley Stoke Community School', 'Bristol'),
  ('Bradon Forest School', 'Swindon'),
  ('Bramcote College', 'Nottingham'),
  ('Bramhall High School', 'Stockport'),
  ('Brampton Manor Academy', 'London'),
  ('Brannel School', 'St Austell'),
  ('Branston Community Academy', 'Lincoln'),
  ('Braunton Academy', 'Braunton'),
  ('Brayton Academy', 'Selby'),
  ('Breckland School', 'Brandon'),
  ('Bredon Hill Academy', 'Evesham'),
  ('Brentford School for Girls', 'Brentford'),
  ('Brentside High School', 'London'),
  ('Brentwood County High School', 'Brentwood'),
  ('Brentwood Ursuline Convent High School', 'Brentwood'),
  ('Brewood Middle CofE Academy', 'Stafford'),
  ('Bridge Learning Campus', 'Bristol'),
  ('Bridgemary School', 'Gosport'),
  ('Bridgewater High School', 'Warrington'),
  ('Bridgnorth Endowed School', 'Bridgnorth'),
  ('Bridgwater College Academy', 'Bridgwater'),
  ('Bridlington School', 'Bridlington'),
  ('Brighouse High School', 'Brighouse'),
  ('Brighton Aldridge Community Academy', 'Brighton'),
  ('Brighton Hill Community School', 'Basingstoke'),
  ('Brigshaw High School', 'Castleford'),
  ('Brimsham Green School', 'Bristol'),
  ('Brine Leas School', 'Nantwich'),
  ('Brinsworth Academy', 'Rotherham'),
  ('Bristnall Hall Academy', 'Oldbury'),
  ('Bristol Brunel Academy', 'Bristol'),
  ('Bristol Cathedral Choir School', 'Bristol'),
  ('Bristol Free School', 'Bristol'),
  ('Bristol Metropolitan Academy', 'Bristol'),
  ('Brixham College', 'Brixham'),
  ('Broadland High Ormiston Academy', 'Norwich'),
  ('Broadoak Academy', 'Weston-Super-Mare'),
  ('Broadoak School', 'Manchester'),
  ('Broadstone Middle School', 'Broadstone'),
  ('Broadwater School', 'Godalming'),
  ('Broadway Academy', 'Birmingham'),
  ('Brockhill Park Performing Arts College', 'Hythe'),
  ('Brockington College', 'Leicester'),
  ('Brompton Academy', 'Gillingham'),
  ('Bronte Girls'' Academy', 'Bradford'),
  ('Brook Mead Academy', 'Leicester'),
  ('Brook Sixth Form and Academy', 'Dagenham'),
  ('Brooke Weston Academy', 'Great Oakley'),
  ('Brookfield Community School', 'Southampton'),
  ('Brookfield Community School', 'Chesterfield'),
  ('Brooklands Middle School', 'Leighton Buzzard'),
  ('Brookvale Groby Learning Campus', 'Leicester'),
  ('Broughton Hall Catholic High School', 'Liverpool'),
  ('Broughton High School', 'Preston'),
  ('Brownedge St Mary''s Catholic High School', 'Preston'),
  ('Brownhills Ormiston Academy', 'Walsall'),
  ('Bruntcliffe Academy', 'Leeds'),
  ('Brymore Academy', 'Bridgwater'),
  ('Buckingham School', 'Buckingham'),
  ('Buckler''s Mead School', 'Yeovil'),
  ('Budehaven Community School', 'Bude'),
  ('Budmouth Academy Weymouth', 'Weymouth'),
  ('Buile Hill Academy', 'Salford'),
  ('Bullers Wood School', 'Chislehurst'),
  ('Bullers Wood School for Boys', 'Bromley'),
  ('Bungay High School', 'Bungay'),
  ('Burford School', 'Burford'),
  ('Burnage Academy for Boys', 'Manchester'),
  ('Burnham Grammar School', 'Slough'),
  ('Burnley High School', 'Burnley'),
  ('Burnside College', 'Wallsend'),
  ('Burnt Mill Academy', 'Harlow'),
  ('Burntwood School', 'London'),
  ('Burscough Priory Academy', 'Ormskirk'),
  ('Bury Church of England High School', 'Bury'),
  ('Bury St Edmunds County High School', 'Bury St Edmunds'),
  ('Bushey Meads School', 'Bushey'),
  ('Buttershaw Business & Enterprise College Academy', 'Bradford'),
  ('Buxton Community School', 'Buxton'),
  ('Buxton School', 'London'),
  ('Caister Academy', 'Great Yarmouth'),
  ('Caistor Grammar School', 'Market Rasen'),
  ('Caistor Yarborough Academy', 'Market Rasen'),
  ('Calday Grange Grammar School', 'Wirral'),
  ('Calderstones School', 'Liverpool'),
  ('Caldew School', 'Carlisle'),
  ('Callerton Academy', 'Newcastle-upon-Tyne'),
  ('Callington Community College', 'Callington'),
  ('Calthorpe Park School', 'Fleet'),
  ('Caludon Castle School', 'Coventry'),
  ('Camborne Science and International Academy', 'Camborne'),
  ('Cambourne Village College', 'Cambridge'),
  ('Cambridge Academy for Science and Technology', 'Cambridge'),
  ('Campion School', 'Northampton'),
  ('Campion School', 'Leamington Spa'),
  ('Campsmount Academy', 'Doncaster'),
  ('Cams Hill School', 'Fareham'),
  ('Canary Wharf College Crossharbour', 'London'),
  ('Cannock Chase High School', 'Cannock'),
  ('Canon Slade School', 'Bolton'),
  ('Canons High School', 'Edgware'),
  ('Cansfield High School', 'Wigan'),
  ('Cantell School', 'Southampton'),
  ('Cape Cornwall School', 'Penzance'),
  ('Cardinal Allen Catholic High School, Fleetwood', 'Fleetwood'),
  ('Cardinal Griffin Catholic College', 'Cannock'),
  ('Cardinal Heenan Catholic High School', 'Liverpool'),
  ('Cardinal Heenan Catholic High School', 'Leeds'),
  ('Cardinal Hume Catholic School, Gateshead', 'Gateshead'),
  ('Cardinal Langley Roman Catholic High School', 'Manchester'),
  ('Cardinal Newman Catholic High School', 'Warrington'),
  ('Cardinal Newman Catholic School', 'Hove'),
  ('Cardinal Newman Catholic School', 'Coventry'),
  ('Cardinal Newman Catholic School A Specialist Science College', 'Luton'),
  ('Cardinal Pole Catholic School', 'London'),
  ('Cardinal Wiseman Catholic School', 'Birmingham'),
  ('Cardinal Wiseman Catholic School', 'Coventry'),
  ('Carisbrooke College', 'Newport'),
  ('Carleton High School', 'Pontefract'),
  ('Carlton Academy', 'Nottingham'),
  ('Carlton Bolling', 'Bradford'),
  ('Carlton Keighley', 'Keighley'),
  ('Carlton le Willows Academy', 'Gedling'),
  ('Carmel College', 'Darlington'),
  ('Carnforth High School', 'Carnforth'),
  ('Caroline Chisholm School', 'Northampton'),
  ('Carr Hill High School', 'Preston'),
  ('Carr Manor Community School', 'Leeds'),
  ('Carre''s Grammar School', 'Sleaford'),
  ('Carrington School', 'Redhill'),
  ('Carshalton Boys Sports College', 'Carshalton'),
  ('Carshalton High School for Girls', 'Carshalton'),
  ('Carterton Community College', 'Carterton'),
  ('Cartmel Priory CofE School', 'Grange-over-Sands'),
  ('Casterton College Rutland', 'Stamford'),
  ('Castle Donington College', 'Derby'),
  ('Castle Hall Academy', 'Mirfield'),
  ('Castle Manor Academy', 'Haverhill'),
  ('Castle Mead Academy', 'Leicester'),
  ('Castle Newnham School', 'Bedford'),
  ('Castle View Academy', 'Portsmouth'),
  ('Castle View Enterprise Academy', 'Sunderland'),
  ('Castle View School', 'Canvey Island'),
  ('Castleford Academy', 'Castleford'),
  ('Caterham High School', 'Ilford'),
  ('Catmose College', 'Oakham'),
  ('Catshill Middle School', 'Bromsgrove'),
  ('Cecil Jones Academy', 'Southend-on-Sea'),
  ('Cedar Mount Academy', 'Gorton'),
  ('Cedars Upper School', 'Leighton Buzzard'),
  ('Central Foundation Boys'' School', 'London'),
  ('Central Foundation Girls'' School', 'London'),
  ('Chace Community School', 'Enfield'),
  ('Chadwell Heath Academy', 'Romford'),
  ('Chailey School', 'Lewes'),
  ('Challney High School for Boys', 'Luton'),
  ('Challney High School for Girls', 'Luton'),
  ('Chancellor''s School', 'Hatfield'),
  ('Chantry Academy', 'Ipswich'),
  ('Chapel-en-le-Frith High School', 'High Peak'),
  ('Charles Darwin School', 'Westerham'),
  ('Charles Read Academy', 'Grantham'),
  ('Charlton School', 'Telford'),
  ('Charnwood College', 'Loughborough'),
  ('Charters School', 'Ascot')
ON CONFLICT (name, town) DO NOTHING;
