-- Chunk 4 of 7 (500 schools)
INSERT INTO public.schools (name, town) VALUES
  ('Lift Maltings', 'Witham'),
  ('Lift New Forest', 'Southampton'),
  ('Lift New Rickstones', 'Witham'),
  ('Lift Rawlett', 'Tamworth'),
  ('Lift Richmond Park', 'London'),
  ('Lift Ryde', 'Ryde'),
  ('Lift Sir Herbert Leon', 'Milton Keynes'),
  ('Lift Tamworth', 'Tamworth'),
  ('Lift Tendring', 'Frinton-on-Sea'),
  ('Lift Unity City', 'Middlesbrough'),
  ('Lift Winton', 'Andover'),
  ('Light Hall School', 'Solihull'),
  ('Lightcliffe Academy', 'Halifax'),
  ('Lilian Baylis Technology School', 'London'),
  ('Limehurst Academy', 'Loughborough'),
  ('Lincoln Castle Academy', 'Lincoln'),
  ('Lincoln Christ''s Hospital School', 'Lincoln'),
  ('Lincoln UTC', 'Lincoln'),
  ('Lincroft Academy', 'Bedford'),
  ('Linslade School', 'Leighton Buzzard'),
  ('Linton Village College', 'Cambridge'),
  ('LIPA School', 'Liverpool'),
  ('Lipson Co-operative Academy', 'Plymouth'),
  ('Liskeard School and Community College', 'Liskeard'),
  ('Lister Community School', 'London'),
  ('Litcham School', 'King''s Lynn'),
  ('Litherland High School', 'Liverpool'),
  ('Little Heath School', 'Reading'),
  ('Little Ilford School', 'London'),
  ('Little Lever School', 'Bolton'),
  ('Littleover Community School', 'Derby'),
  ('Liverpool College', 'Liverpool'),
  ('Liverpool Life Sciences UTC', 'Liverpool'),
  ('Livingstone Academy Bournemouth', 'Bournemouth'),
  ('Lockyer''s Middle School', 'Wimborne'),
  ('Lode Heath School', 'Solihull'),
  ('Lodge Park Academy', 'Corby'),
  ('Logic Studio School', 'Feltham'),
  ('London Academy', 'Edgware'),
  ('London Design and Engineering UTC', 'London'),
  ('London Enterprise Academy', 'London'),
  ('London Nautical, City of London Academy', 'London'),
  ('Long Field Spencer Academy', 'Melton Mowbray'),
  ('Long Stratton High School', 'Norwich'),
  ('Longbenton High School', 'Newcastle-upon-Tyne'),
  ('Longcroft School and Sixth Form College', 'Beverley'),
  ('Longdean School', 'Hemel Hempstead'),
  ('Longdendale High School', 'Hyde'),
  ('Longfield Academy', 'Darlington'),
  ('Longhill High School', 'Brighton'),
  ('Longridge High School', 'Preston'),
  ('Longsands Academy', 'St Neots'),
  ('Looe Community Academy', 'Looe'),
  ('Lord Derby Academy', 'Liverpool'),
  ('Lord Grey Academy', 'Milton Keynes'),
  ('Lord Lawson of Beamish Academy', 'Chester le Street'),
  ('Lord Williams''s School', 'Thame'),
  ('Lordswood Boys'' School', 'Birmingham'),
  ('Loreto College', 'St Albans'),
  ('Loreto Grammar School', 'Altrincham'),
  ('Loreto High School Chorlton', 'Manchester'),
  ('Lostock Hall Academy', 'Preston'),
  ('Lostock High School', 'Manchester'),
  ('Louth Academy', 'Louth'),
  ('Lowton Church of England High School', 'Warrington'),
  ('Loxford School', 'Ilford'),
  ('Lubavitch House School (Senior Girls)', 'London'),
  ('Ludlow Church of England School', 'Ludlow'),
  ('Lutterworth College', 'Lutterworth'),
  ('Lutterworth High School', 'Lutterworth'),
  ('Lydiard Park Academy', 'Swindon'),
  ('Lymm High School', 'Lymm'),
  ('Lynch Hill Enterprise Academy', 'Slough'),
  ('Lyndon School', 'Solihull'),
  ('Lyng Hall School', 'Coventry'),
  ('Lynn Grove Academy', 'Great Yarmouth'),
  ('Lytchett Minster School', 'Poole'),
  ('Lytham St Annes High School', 'Lytham St. Annes'),
  ('Macmillan Academy', 'Middlesbrough'),
  ('Madani Boys School', 'Leicester'),
  ('Madani Girls'' School', 'Leicester'),
  ('Madeley Academy', 'Telford'),
  ('Madeley High School', 'Crewe'),
  ('Magdalen College School', 'Brackley'),
  ('Maghull High School', 'Liverpool'),
  ('Magna Academy', 'Poole'),
  ('Magnus Church of England Academy', 'Newark'),
  ('Maharishi Free School', 'Ormskirk'),
  ('Maiden Erlegh Chiltern Edge', 'Reading'),
  ('Maiden Erlegh School', 'Reading'),
  ('Maiden Erlegh School in Reading', 'Reading'),
  ('Maidenhill School', 'Stonehouse'),
  ('Maidstone Grammar School', 'Maidstone'),
  ('Maidstone Grammar School for Girls', 'Maidstone'),
  ('Malbank School and Sixth Form College', 'Nantwich'),
  ('Malcolm Arnold Academy', 'Northampton'),
  ('Malet Lambert', 'Hull'),
  ('Malmesbury School', 'Malmesbury'),
  ('Maltby Academy', 'Rotherham'),
  ('Malton School', 'Malton'),
  ('Manchester Academy', 'Manchester'),
  ('Manchester Communication Academy', 'Manchester'),
  ('Manchester Enterprise Academy', 'Wythenshawe'),
  ('Manchester Enterprise Academy Central', 'Manchester'),
  ('Manchester Mesivta School', 'Prestwich'),
  ('Mangotsfield School', 'Bristol'),
  ('Manningtree High School', 'Manningtree'),
  ('Manor Church of England Academy', 'York'),
  ('Manor Community Academy', 'Hartlepool'),
  ('Manor Croft Academy', 'Dewsbury'),
  ('Manor Drive Secondary Academy', 'Peterborough'),
  ('Manor High School', 'Leicester'),
  ('Manor School', 'Wellingborough'),
  ('Manshead Church of England Academy', 'Luton'),
  ('Marden Bridge Middle School', 'Whitley Bay'),
  ('Marden High School', 'North Shields'),
  ('Maria Fidelis Catholic School FCJ', 'London'),
  ('Maricourt Catholic High School', 'Liverpool'),
  ('Marine Academy Plymouth', 'Plymouth'),
  ('Maritime Academy', 'Rochester'),
  ('Mark Hall Academy', 'Harlow'),
  ('Mark Rutherford School', 'Bedford'),
  ('Marling School', 'Stroud'),
  ('Marlwood School', 'Bristol'),
  ('Marple Hall School', 'Stockport'),
  ('Marriotts School', 'Stevenage'),
  ('Marsden Heights Community College', 'Nelson'),
  ('Marshalls Park Academy', 'Romford'),
  ('Marshland High School', 'Wisbech'),
  ('Marston Vale Middle School', 'Bedford'),
  ('Mary Webb School and Science College', 'Shrewsbury'),
  ('Marylebone Boys'' School', 'London'),
  ('Matford Brook Academy', 'Exeter'),
  ('Matravers School', 'Westbury'),
  ('Matthew Arnold School', 'Oxford'),
  ('Matthew Moss High School', 'Rochdale'),
  ('Mayfield Grammar School, Gravesend', 'Gravesend'),
  ('Mayfield School', 'Dagenham'),
  ('Mayfield School', 'Portsmouth'),
  ('Mayflower High School', 'Billericay'),
  ('Meadow Park School', 'Coventry'),
  ('Meadowhead School Academy Trust', 'Sheffield'),
  ('Meden School', 'Mansfield'),
  ('Medina College', 'Newport'),
  ('Melbourn Village College', 'Royston'),
  ('Melior Community Academy', 'Scunthorpe'),
  ('Melksham Oak Community School', 'Melksham'),
  ('Menorah High School for Girls', 'London'),
  ('Meole Brace School', 'Shrewsbury'),
  ('Meols Cop High School', 'Southport'),
  ('Meopham School', 'Gravesend'),
  ('Mercia Academy', 'Swadlincote'),
  ('Mercia School', 'Sheffield'),
  ('Meridian High School', 'Croydon'),
  ('Merstham Park School', 'Redhill'),
  ('Michaela Community School', 'London'),
  ('Middleton Technology School', 'Manchester'),
  ('Middlewich High School', 'Middlewich'),
  ('Midhurst Rother College', 'Midhurst'),
  ('Mildenhall College Academy', 'Mildenhall'),
  ('Mill Hill County High School', 'London'),
  ('Millais School', 'Horsham'),
  ('Millbay Academy', 'Plymouth'),
  ('Millfield Science & Performing Arts College', 'Thornton-Cleveleys'),
  ('Millom School', 'Millom'),
  ('Millthorpe School', 'York'),
  ('Miltoncross Academy', 'Portsmouth'),
  ('Minehead Middle School', 'Minehead'),
  ('Minerva Virtual Academy', 'London'),
  ('Minsthorpe Community College', 'Pontefract'),
  ('Moat Community College', 'Leicester'),
  ('Monk''s Walk School', 'Welwyn Garden City'),
  ('Monkseaton High School', 'Whitley Bay'),
  ('Monkseaton Middle School', 'Whitley Bay'),
  ('Monkton Wood Academy', 'Taunton'),
  ('Monkwearmouth Academy', 'Sunderland'),
  ('Montgomery Academy', 'Blackpool'),
  ('Montsaye Academy', 'Kettering'),
  ('Moor End Academy', 'Huddersfield'),
  ('Moor Park High School and Sixth Form', 'Preston'),
  ('Moorside High School', 'Manchester'),
  ('Moorside High School', 'Stoke-on-Trent'),
  ('Morecambe Bay Academy', 'Morecambe'),
  ('Moreton School', 'Wolverhampton'),
  ('Morpeth Chantry Middle School', 'Morpeth'),
  ('Morpeth Newminster Middle School', 'Morpeth'),
  ('Morpeth School', 'London'),
  ('Mortimer Community College', 'South Shields'),
  ('Moseley Park', 'Bilston'),
  ('Moseley School and Sixth Form', 'Birmingham'),
  ('Mossbourne Community Academy', 'London'),
  ('Mossbourne Fobbing Academy', 'Stanford-le-Hope'),
  ('Mossbourne Port Side Academy', 'Stanford-le-Hope'),
  ('Mossbourne Victoria Park Academy', 'London'),
  ('Mossley Hollins High School', 'Ashton-under-Lyne'),
  ('Moulsham High School', 'Chelmsford'),
  ('Moulton School and Science College', 'Northampton'),
  ('Mount Carmel Roman Catholic High School, Hyndburn', 'Accrington'),
  ('Mount St Joseph RC High School a Voluntary Academy', 'Bolton'),
  ('Mount St Mary''s Catholic High School', 'Leeds'),
  ('Mounts Bay Academy', 'Penzance'),
  ('Mulberry Academy London Dock', 'London'),
  ('Mulberry Academy Shoreditch', 'London'),
  ('Mulberry Academy Woodside', 'London'),
  ('Mulberry School for Girls', 'London'),
  ('Mulberry Stepney Green Mathematics and Computing College', 'London'),
  ('Mulberry UTC', 'London'),
  ('Mullion School', 'Helston'),
  ('Murray Park Community School', 'Derby'),
  ('Myton School', 'Warwick'),
  ('Nailsea School', 'Bristol'),
  ('NCEA Duke''s Secondary School', 'Ashington'),
  ('Neale-Wade Academy', 'March'),
  ('Nene Park Academy', 'Peterborough'),
  ('Neston High School', 'Neston'),
  ('Nether Stowe School', 'Lichfield'),
  ('Netherhall Learning Campus High School', 'Select'),
  ('Netherhall School', 'Maryport'),
  ('Netherthorpe School', 'Chesterfield'),
  ('Netherwood Academy', 'Barnsley'),
  ('New Line Learning Academy', 'Maidstone'),
  ('New Mills School', 'High Peak'),
  ('New Road Academy', 'Telford'),
  ('Newcastle Academy', 'Newcastle Under Lyme'),
  ('Newent Community School and Sixth Form Centre', 'Newent'),
  ('Newfield Secondary School', 'Sheffield'),
  ('Newhouse Academy', 'Heywood'),
  ('Newland School for Girls', 'Hull'),
  ('Newlands Girls'' School', 'Maidenhead'),
  ('Newman Catholic College', 'London'),
  ('Newmarket Academy', 'Newmarket'),
  ('Newport Girls'' High School Academy', 'Newport'),
  ('Newquay Tretherras', 'Newquay'),
  ('Newsome Academy', 'Huddersfield'),
  ('Newstead Wood School', 'Orpington'),
  ('Newton Abbot College', 'Newton Abbot'),
  ('Nicholas Breakspear Catholic School', 'St Albans'),
  ('Nicholas Chamberlaine School', 'Bedworth'),
  ('Nidderdale High School', 'Harrogate'),
  ('Ninestiles, an Academy', 'Birmingham'),
  ('Nishkam High School', 'Birmingham'),
  ('Nishkam School West London', 'Osterley'),
  ('Noadswood School', 'Southampton'),
  ('Noel-Baker Academy', 'Derby'),
  ('Nonsuch High School for Girls', 'Sutton'),
  ('Norbury High School for Girls', 'Thornton Heath'),
  ('Norham High School', 'North Shields'),
  ('Norlington School and 6th Form', 'London'),
  ('North Brent School', 'London'),
  ('North Bromsgrove High School', 'Bromsgrove'),
  ('North Cambridge Academy', 'Cambridge'),
  ('North Cestrian School', 'Altrincham'),
  ('North Chadderton School', 'Oldham'),
  ('North Durham Academy', 'Stanley'),
  ('North East Futures UTC', 'Newcastle Upon Tyne'),
  ('North Gosforth Academy', 'Newcastle-upon-Tyne'),
  ('North Huddersfield Trust School', 'Huddersfield'),
  ('North Kesteven Academy', 'Lincoln'),
  ('North Leamington School', 'Leamington Spa'),
  ('North Liverpool Academy', 'Liverpool'),
  ('North Oxfordshire Academy', 'Banbury'),
  ('North Shore Academy', 'Stockton-on-Tees'),
  ('North Walsham High School', 'North Walsham'),
  ('Northallerton School & Sixth Form College', 'Northallerton'),
  ('Northampton Academy', 'Northampton'),
  ('Northampton International Academy', 'Northampton'),
  ('Northampton School', 'Northampton'),
  ('Northampton School for Boys', 'Northampton'),
  ('Northampton School for Girls', 'Northampton'),
  ('Northfield School and Sports College', 'Billingham'),
  ('Northfleet School for Girls', 'Gravesend'),
  ('Northfleet Technology College', 'Gravesend'),
  ('Northgate High School', 'Ipswich'),
  ('Northgate High School', 'Dereham'),
  ('Northstowe Learning Community', 'Cambridge'),
  ('Northwood School', 'Northwood'),
  ('Norton Canes High School', 'Cannock'),
  ('Norton College', 'Malton'),
  ('Norton Hill Academy', 'Radstock'),
  ('Notley High School and Braintree Sixth Form', 'Braintree'),
  ('Notre Dame Catholic Academy', 'Liverpool'),
  ('Notre Dame Catholic Girls'' School', 'London'),
  ('Notre Dame High School', 'Sheffield'),
  ('Notre Dame High School, Norwich', 'Norwich'),
  ('Notre Dame RC School', 'Plymouth'),
  ('Nottingham Academy', 'Nottingham'),
  ('Nottingham Free School', 'Nottingham'),
  ('Nottingham Girls'' Academy', 'Nottingham'),
  ('Nottingham University Academy of Science and Technology', 'Nottingham'),
  ('Nottingham University Samworth Academy', 'Nottingham'),
  ('Nova Hreod Academy', 'Swindon'),
  ('Nower Hill High School', 'Pinner'),
  ('Nuneaton Academy', 'Nuneaton'),
  ('Nunnery Wood High School', 'Worcester'),
  ('Nunthorpe Academy', 'Middlesbrough'),
  ('Oak Academy', 'Bournemouth'),
  ('Oak Wood School', 'Uxbridge'),
  ('Oakbank School', 'Reading'),
  ('Oakfield Academy', 'Frome'),
  ('Oakgrove School', 'Milton Keynes'),
  ('Oaklands Catholic School', 'Waterlooville'),
  ('Oaklands School', 'London'),
  ('Oakley School', 'Bishops Tachbrook'),
  ('Oakmoor School', 'Bordon'),
  ('Oaks Park High School', 'Ilford'),
  ('Oaks Park High School', 'Carshalton'),
  ('Oakwood High School', 'Rotherham'),
  ('Oakwood Park Grammar School', 'Maidstone'),
  ('Oakwood School', 'Horley'),
  ('Oasis Academy Arena', 'London'),
  ('Oasis Academy Brightstowe', 'Bristol'),
  ('Oasis Academy Brislington', 'Bristol'),
  ('Oasis Academy Coulsdon', 'Croydon'),
  ('Oasis Academy Daventry Road', 'Bristol'),
  ('Oasis Academy Don Valley', 'Sheffield'),
  ('Oasis Academy Enfield', 'Enfield'),
  ('Oasis Academy Hadley', 'Enfield'),
  ('Oasis Academy Immingham', 'Immingham'),
  ('Oasis Academy John Williams', 'Bristol'),
  ('Oasis Academy Leesbrook', 'Oldham'),
  ('Oasis Academy Lister Park', 'Bradford'),
  ('Oasis Academy Lord''s Hill', 'Southampton'),
  ('Oasis Academy Mayfield', 'Southampton'),
  ('Oasis Academy MediaCityUK', 'Manchester'),
  ('Oasis Academy Oldham', 'Oldham'),
  ('Oasis Academy Shirley Park', 'Croydon'),
  ('Oasis Academy Sholing', 'Southampton'),
  ('Oasis Academy Silvertown', 'London'),
  ('Oasis Academy South Bank', 'London'),
  ('Oasis Academy Temple Quarter', 'Bristol'),
  ('Oasis Academy Wintringham', 'Grimsby'),
  ('Oathall Community College', 'Haywards Heath'),
  ('Okehampton College', 'Okehampton'),
  ('Old Buckenham High School', 'Attleborough'),
  ('Old Swinford Hospital', 'Stourbridge'),
  ('Oldbury Academy', 'Oldbury'),
  ('Oldbury Wells School', 'Bridgnorth'),
  ('Oldfield School', 'Bath'),
  ('Oldfields Hall Middle School', 'Uttoxeter'),
  ('Onslow St Audrey''s School', 'Hatfield'),
  ('Orchard Mead Academy', 'Leicester'),
  ('Orchard Park High School', 'Croydon'),
  ('Orchard School Bristol', 'Bristol'),
  ('Orchards Academy', 'Swanley'),
  ('Oriel High School', 'Crawley'),
  ('Orion Coopers', 'Chislehurst'),
  ('Orion Eden Park', 'Beckenham'),
  ('Orion Spires', 'Canterbury'),
  ('Orleans Park School', 'Twickenham'),
  ('Ormiston Bolingbroke Academy', 'Runcorn'),
  ('Ormiston Bushfield Academy', 'Peterborough'),
  ('Ormiston Chadwick Academy', 'Widnes'),
  ('Ormiston Denes Academy', 'Lowestoft'),
  ('Ormiston Endeavour Academy', 'Ipswich'),
  ('Ormiston Forge Academy', 'Cradley Heath'),
  ('Ormiston Horizon Academy', 'Stoke on Trent'),
  ('Ormiston Ilkeston Enterprise Academy', 'Ilkeston'),
  ('Ormiston Maritime Academy', 'Grimsby'),
  ('Ormiston Meridian Academy', 'Stoke-on-Trent'),
  ('Ormiston NEW Academy', 'Wolverhampton'),
  ('Ormiston Park Academy', 'South Ockendon'),
  ('Ormiston Rivers Academy', 'Burnham-on-Crouch'),
  ('Ormiston Sandwell Community Academy', 'Oldbury'),
  ('Ormiston Shelfield Community Academy', 'Walsall'),
  ('Ormiston Sir Stanley Matthews Academy', 'Stoke-on-Trent'),
  ('Ormiston Six Villages Academy', 'Chichester'),
  ('Ormiston Sudbury Academy', 'Sudbury'),
  ('Ormiston SWB Academy', 'Bilston'),
  ('Ormiston Venture Academy', 'Gorleston'),
  ('Ormiston Victory Academy', 'Norwich'),
  ('Ormskirk School', 'Ormskirk'),
  ('Orsett Heath Academy', 'Grays'),
  ('Ossett Academy and Sixth Form College', 'Ossett'),
  ('Otley Prince Henry''s Grammar School Specialist Language College', 'Otley'),
  ('Oulder Hill Leadership Academy', 'Rochdale'),
  ('Oulton Academy', 'Leeds'),
  ('Our Lady & St. Bede Catholic Academy', 'Stockton-on-Tees'),
  ('Our Lady and St Chad Catholic Academy', 'Wolverhampton'),
  ('Our Lady and St John RC High School, a Voluntary Academy', 'Blackburn'),
  ('Our Lady Queen of Peace Catholic High School', 'Skelmersdale'),
  ('Our Lady''s Catholic College', 'Lancaster'),
  ('Our Lady''s Catholic High School', 'Preston'),
  ('Our Lady''s RC High School', 'Manchester'),
  ('Outwood Academy Acklam', 'Middlesbrough'),
  ('Outwood Academy Adwick', 'Doncaster'),
  ('Outwood Academy Bishopsgarth', 'Stockton-on-Tees'),
  ('Outwood Academy Brumby', 'Scunthorpe'),
  ('Outwood Academy Bydales', 'Redcar'),
  ('Outwood Academy Carlton', 'Barnsley'),
  ('Outwood Academy City', 'Sheffield'),
  ('Outwood Academy City Fields', 'Wakefield'),
  ('Outwood Academy Danum', 'Doncaster'),
  ('Outwood Academy Easingwold', 'York'),
  ('Outwood Academy Foxhills', 'Scunthorpe'),
  ('Outwood Academy Freeston', 'Normanton'),
  ('Outwood Academy Hasland Hall', 'Chesterfield'),
  ('Outwood Academy Haydock', 'St. Helens'),
  ('Outwood Academy Hemsworth', 'Pontefract'),
  ('Outwood Academy Hindley', 'Wigan'),
  ('Outwood Academy Kirkby', 'Nottingham'),
  ('Outwood Academy Newbold', 'Chesterfield'),
  ('Outwood Academy Normanby', 'Middlesbrough'),
  ('Outwood Academy Ormesby', 'Middlesbrough'),
  ('Outwood Academy Portland', 'Worksop'),
  ('Outwood Academy Redcar', 'Redcar'),
  ('Outwood Academy Ripon', 'Ripon'),
  ('Outwood Academy Riverside', 'Middlesbrough'),
  ('Outwood Academy Shafton', 'Barnsley'),
  ('Outwood Academy Valley', 'Worksop'),
  ('Outwood Grange Academy', 'Wakefield'),
  ('Overton Grange School', 'Sutton'),
  ('Ovingham Middle School', 'Prudhoe'),
  ('Oxclose Community Academy', 'Washington'),
  ('Oxford Spires Academy', 'Oxford'),
  ('Oxted School', 'Oxted'),
  ('Paddington Academy', 'London'),
  ('Padgate Academy', 'Warrington'),
  ('Paget High School', 'Burton-on-Trent'),
  ('Paignton Academy', 'Paignton'),
  ('Painsley Catholic College', 'Stoke-on-Trent'),
  ('Pakefield High School', 'Lowestoft'),
  ('Park Academy West London', 'Hillingdon'),
  ('Park Community School', 'Havant'),
  ('Park Hall Academy', 'Birmingham'),
  ('Park High School', 'Stanmore'),
  ('Park House School', 'Newbury'),
  ('Park Lane Academy', 'Halifax'),
  ('Park Vale Academy', 'Nottingham'),
  ('Park View School', 'London'),
  ('Park View School', 'Chester le Street'),
  ('Parkfields Middle School', 'Dunstable'),
  ('Parklands High School', 'Chorley'),
  ('Parkside Academy', 'Crook'),
  ('Parkside Community College', 'Cambridge'),
  ('Parkside Community School', 'Chesterfield'),
  ('Parkside Middle School', 'Bromsgrove'),
  ('Parkside School', 'Bradford'),
  ('Parkside Studio College', 'Hayes'),
  ('Parkstone Grammar School', 'Poole'),
  ('Parliament Hill School', 'London'),
  ('Parmiter''s School', 'Watford'),
  ('Parrenthorn High School', 'Manchester'),
  ('Parrs Wood High School', 'Manchester'),
  ('Passmores Academy', 'Harlow'),
  ('Patcham High School', 'Brighton'),
  ('Patchway Community School', 'Almondsbury'),
  ('Pate''s Grammar School', 'Cheltenham'),
  ('Paulet High School', 'Burton-on-Trent'),
  ('Paxman Academy', 'Colchester'),
  ('Peacehaven Community School', 'Peacehaven'),
  ('Pegasus Academy', 'Dudley'),
  ('Penair School', 'Truro'),
  ('Pendle Vale College', 'Nelson'),
  ('Penistone Grammar School', 'Sheffield'),
  ('Penketh High School', 'Warrington'),
  ('Penkridge Middle School', 'Stafford'),
  ('Penrice Academy', 'St Austell'),
  ('Penryn College', 'Penryn'),
  ('Pensby High School', 'Wirral'),
  ('Penwortham Girls'' High School', 'Preston'),
  ('Penwortham Priory Academy', 'Preston'),
  ('Perins School', 'Alresford'),
  ('Perryfields Academy', 'Oldbury'),
  ('Pershore High School', 'Pershore'),
  ('Perton Middle School', 'Wolverhampton'),
  ('Pewsey Vale School', 'Pewsey'),
  ('Philip Morant School and College', 'Colchester'),
  ('Philips High School', 'Manchester'),
  ('Phoenix Academy', 'London'),
  ('Pilton Community College', 'Barnstaple'),
  ('Pimlico Academy', 'London'),
  ('Pinner High School', 'Pinner'),
  ('Pioneer Secondary Academy', 'Stoke Poges'),
  ('Pittville School', 'Cheltenham'),
  ('Pix Brook Academy', 'Stotfold'),
  ('Plantsbrook School', 'Sutton Coldfield'),
  ('Plashet, City of London Academy', 'London'),
  ('Platanos College', 'London'),
  ('Pleckgate High School', 'Blackburn'),
  ('Plume School', 'Maldon'),
  ('Plumstead Manor School', 'London'),
  ('Plymouth High School for Girls', 'Plymouth'),
  ('Plympton Academy', 'Plymouth'),
  ('Plymstock School', 'Plymouth'),
  ('Polam Hall School', 'Darlington'),
  ('Poltair School', 'St Austell'),
  ('Ponteland High School', 'Ponteland'),
  ('Pool Academy', 'Redruth'),
  ('Pool Hayes Academy', 'Willenhall'),
  ('Poole Grammar School', 'Poole'),
  ('Poole High School', 'Poole'),
  ('Portchester Community School', 'Fareham'),
  ('Portslade Aldridge Community Academy', 'Brighton'),
  ('Poynton High School', 'Stockport'),
  ('Prendergast Ladywell School', 'Lewisham'),
  ('Prendergast School', 'London'),
  ('Prendergast Vale School', 'London'),
  ('Prenton High School for Girls', 'Birkenhead'),
  ('Presdales School', 'Ware'),
  ('President Kennedy School Academy', 'Coventry')
ON CONFLICT (name, town) DO NOTHING;
