-- Chunk 2 of 7 (500 schools)
INSERT INTO public.schools (name, town) VALUES
  ('Chase High School', 'Westcliff-on-Sea'),
  ('Chase Terrace Academy', 'Burntwood'),
  ('Chatham & Clarendon Grammar School', 'Ramsgate'),
  ('Chatham Grammar', 'Chatham'),
  ('Chaucer School', 'Sheffield'),
  ('Cheadle Hulme High School', 'Cheadle'),
  ('Cheam High School', 'Sutton'),
  ('Chellaston Academy', 'Derby'),
  ('Chelmer Valley High School', 'Chelmsford'),
  ('Chelmsford County High School for Girls', 'Chelmsford'),
  ('Chelsea Academy', 'London'),
  ('Cheltenham Bournside School and Sixth Form Centre', 'Cheltenham'),
  ('Chenderit School', 'Banbury'),
  ('Cheney School', 'Oxford'),
  ('Chertsey High School', 'Addlestone'),
  ('Chesham Grammar School', 'Chesham'),
  ('Cheshire Studio School', 'Crewe'),
  ('Cheslyn Hay Academy', 'Walsall'),
  ('Chessington School', 'Chessington'),
  ('Chester International School', 'Chester'),
  ('Chesterfield High School', 'Liverpool'),
  ('Chesterton Community College', 'Cambridge'),
  ('Chesterton Community Sports College', 'Newcastle'),
  ('Chestnut Grove Academy', 'London'),
  ('Chetwynde School', 'Barrow-in-Furness'),
  ('Chew Valley School', 'Bristol'),
  ('Chichester Free School', 'Chichester'),
  ('Chichester High School', 'Chichester'),
  ('Childwall Sports & Science Academy', 'Liverpool'),
  ('Chilmington Green School', 'Great Chart'),
  ('Chiltern Academy', 'Luton'),
  ('Chiltern Hills Academy', 'Chesham'),
  ('Chilton Trinity School', 'Bridgwater'),
  ('Chilwell School', 'Nottingham'),
  ('Chingford Foundation School', 'London'),
  ('Chipping Campden School', 'Chipping Campden'),
  ('Chipping Norton School', 'Chipping Norton'),
  ('Chipping Sodbury School', 'Bristol'),
  ('Chislehurst and Sidcup Grammar School', 'Sidcup'),
  ('Chislehurst School for Girls', 'Chislehurst'),
  ('Chiswick School', 'London'),
  ('Chorlton High School', 'Manchester'),
  ('Chosen Hill School', 'Gloucester'),
  ('Christ Church Academy', 'Stone'),
  ('Christ Church, Church of England Secondary Academy', 'Birmingham'),
  ('Christ The King Catholic High School', 'Preston'),
  ('Christ The King Catholic High School and Sixth Form Centre', 'Southport'),
  ('Christ The King College', 'Newport'),
  ('Christ The King Voluntary Academy', 'Nottingham'),
  ('Christ''s Church of England Comprehensive Secondary School', 'Richmond'),
  ('Christ''s College', 'Sunderland'),
  ('Christ''s College Finchley', 'London'),
  ('Christ''s College, Guildford', 'Guildford'),
  ('Christleton High School', 'Chester'),
  ('Christopher Whitehead Language College', 'Worcester'),
  ('CHS South', 'Manchester'),
  ('Chulmleigh Community College', 'Chulmleigh'),
  ('Church Hill Middle School', 'Redditch'),
  ('Church Stretton School', 'Church Stretton'),
  ('Churchdown School', 'Gloucester'),
  ('Churchill Academy & Sixth Form', 'Winscombe'),
  ('Churchill Community College', 'Wallsend'),
  ('Churchmead Church of England (VA) School', 'Slough'),
  ('Churnet View Middle School', 'Leek'),
  ('Churston Ferrers Grammar School Academy', 'Brixham'),
  ('Cirencester Deer Park School', 'Cirencester'),
  ('Cirencester Kingshill School', 'Cirencester'),
  ('City Academy', 'Birmingham'),
  ('City Academy Norwich', 'Norwich'),
  ('City Heights E-ACT Academy', 'London'),
  ('City of Derby Academy', 'Derby'),
  ('City of London Academy (Southwark)', 'London'),
  ('City of London Academy Highbury Grove', 'London'),
  ('City of London Academy Islington', 'London'),
  ('City of London Academy, Highgate Hill', 'London'),
  ('City of London Academy, Shoreditch Park', 'London'),
  ('City of Norwich School, An Ormiston Academy', 'Norwich'),
  ('City of Peterborough Academy', 'Peterborough'),
  ('Clacton County High School', 'Clacton-on-Sea'),
  ('Clapton Girls'' Academy', 'London'),
  ('Claremont High School', 'Harrow'),
  ('Clarion', 'London'),
  ('Claverham Community College', 'Battle'),
  ('Claydon High School', 'Ipswich'),
  ('Clayton Hall Academy', 'Newcastle-under-Lyme'),
  ('Cleethorpes Academy', 'Cleethorpes'),
  ('Cleeve Park School', 'Sidcup'),
  ('Cleeve School', 'Cheltenham'),
  ('Clevedon School', 'Clevedon'),
  ('Cliff Park Ormiston Academy', 'Great Yarmouth'),
  ('Clifton Community School', 'Rotherham'),
  ('Clitheroe Royal Grammar School', 'Clitheroe'),
  ('Clyst Vale Community College', 'Exeter'),
  ('Co-op Academy Bebington', 'Wirral'),
  ('Co-op Academy Belle Vue', 'Manchester'),
  ('Co-op Academy Failsworth', 'Manchester'),
  ('Co-op Academy Florence MacWilliams', 'Stoke-on-Trent'),
  ('Co-op Academy Grange', 'Bradford'),
  ('Co-op Academy Leeds', 'Leeds'),
  ('Co-op Academy Manchester', 'Manchester'),
  ('Co-op Academy North Manchester', 'Manchester'),
  ('Co-op Academy Priesthorpe', 'Pudsey'),
  ('Co-op Academy Stoke-On-Trent', 'Stoke-on-Trent'),
  ('Co-op Academy Swinton', 'Manchester'),
  ('Co-op Academy Walkden', 'Manchester'),
  ('Cobham Free School', 'Cobham'),
  ('Cockburn John Charles Academy', 'Leeds'),
  ('Cockburn Laurence Calvert Academy', 'Leeds'),
  ('Cockburn School', 'Leeds'),
  ('Cockermouth School', 'Cockermouth'),
  ('Cockshut Hill School', 'Birmingham'),
  ('Codsall Community High School', 'Wolverhampton'),
  ('Codsall Middle School', 'Wolverhampton'),
  ('Colchester Academy', 'Colchester'),
  ('Colchester County High School for Girls', 'Colchester'),
  ('Colchester Royal Grammar School', 'Colchester'),
  ('Coleridge Community College', 'Cambridge'),
  ('Collingwood College', 'Camberley'),
  ('Colmers School and Sixth Form College', 'Birmingham'),
  ('Colne Community School', 'Colchester'),
  ('Colne Park High School', 'Colne'),
  ('Colne Primet Academy', 'Colne'),
  ('Colne Valley High School', 'Huddersfield'),
  ('Coloma Convent Girls'' School', 'Croydon'),
  ('Colonel Frank Seely Academy', 'Nottingham'),
  ('Colton Hills Community School', 'Wolverhampton'),
  ('Colyton Grammar School', 'Colyton'),
  ('Comberton Village College', 'Cambridge'),
  ('Congleton High School', 'Congleton'),
  ('Conisborough College', 'London'),
  ('Connaught School for Girls', 'London'),
  ('Consett Academy', 'Consett'),
  ('Conyers School', 'Yarm'),
  ('Coombe Boys'' School', 'New Malden'),
  ('Coombe Dean School', 'Plymouth'),
  ('Coombe Girls'' School', 'New Malden'),
  ('Coombe Wood School', 'South Croydon'),
  ('Coombeshead Academy', 'Newton Abbot'),
  ('Copleston High School', 'Ipswich'),
  ('Copley Academy', 'Stalybridge'),
  ('Coppice Performing Arts School', 'Wolverhampton'),
  ('Copthall School', 'London'),
  ('Corbridge Middle School', 'Corbridge'),
  ('Corby Business Academy', 'Corby'),
  ('Corby Technical School', 'Corby'),
  ('Corfe Hills School', 'Broadstone'),
  ('Cornwallis Academy', 'Maidstone'),
  ('Corpus Christi Catholic College, A Voluntary Academy', 'Leeds'),
  ('Corpus Christi Catholic High School', 'Preston'),
  ('Cotham School', 'Bristol'),
  ('Cottenham Village College', 'Cambridge'),
  ('Cottingham High School', 'Cottingham'),
  ('Coundon Court', 'Coventry'),
  ('Countesthorpe Academy', 'Countesthorpe'),
  ('Court Fields School', 'Wellington'),
  ('Court Moor School', 'Fleet'),
  ('Cove School', 'Farnborough'),
  ('Cowes Enterprise College, An Ormiston Academy', 'Cowes'),
  ('Cowley Academy', 'Spalding'),
  ('Cowley International College', 'St Helens'),
  ('Cox Green School', 'Maidenhead'),
  ('Cramlington Learning Village', 'Cramlington'),
  ('Cranborne Middle School', 'Wimborne'),
  ('Cranbourne', 'Basingstoke'),
  ('Cranbrook Education Campus', 'Exeter'),
  ('Cranbrook School', 'Cranbrook'),
  ('Cranford Community College', 'Hounslow'),
  ('Crawshaw Academy', 'Pudsey'),
  ('Cressex Community School', 'High Wycombe'),
  ('Crestwood Community School', 'Eastleigh'),
  ('Crewe Engineering and Design UTC', 'Crewe'),
  ('Crispin School Academy', 'Street'),
  ('Crofton Academy', 'Wakefield'),
  ('Crofton School', 'Fareham'),
  ('Cromer Academy', 'Cromer'),
  ('Cromwell Community College', 'Chatteris'),
  ('Crookhorn College', 'Waterlooville'),
  ('Crown Hills Community College', 'Leicester'),
  ('Croxley Danes School', 'Rickmansworth'),
  ('Culcheth High School', 'Warrington'),
  ('Cullompton Community College', 'Cullompton'),
  ('Cumberland Community School', 'London'),
  ('Da Vinci Academy', 'Derby'),
  ('Dagenham Park CofE School', 'Dagenham'),
  ('Dallam School', 'Cumbria'),
  ('Dame Alice Owen''s School', 'Potters Bar'),
  ('Dame Elizabeth Cadbury School', 'Birmingham'),
  ('Dane Court Grammar School', 'Broadstairs'),
  ('Danebury School', 'Stockbridge'),
  ('Danesfield Church of England Voluntary Controlled Community Middle School', 'Taunton'),
  ('Darrick Wood School', 'Orpington'),
  ('Dartford Grammar School', 'Dartford'),
  ('Dartford Grammar School for Girls', 'Dartford'),
  ('Dartford Science & Technology College', 'Dartford'),
  ('Dartmouth Academy', 'Dartmouth'),
  ('Darton Academy', 'Barnsley'),
  ('Darwen Aldridge Community Academy', 'Darwen'),
  ('Darwen Aldridge Enterprise Studio', 'Darwen'),
  ('Darwen Vale High School', 'Darwen'),
  ('Daubeney Academy', 'Bedford'),
  ('Davenant Foundation School', 'Loughton'),
  ('David Nieper Academy', 'Alfreton'),
  ('Davison Church of England High School for Girls, Worthing', 'Worthing'),
  ('Dawlish College', 'Dawlish'),
  ('De Aston School', 'Market Rasen'),
  ('De La Salle School', 'Basildon'),
  ('De La Salle School', 'St. Helens'),
  ('De Lacy Academy', 'Knottingley'),
  ('De Lisle College Loughborough Leicestershire', 'Loughborough'),
  ('De Salis Studio College', 'Hayes'),
  ('de Stafford School', 'Caterham'),
  ('De Warenne Academy', 'Doncaster'),
  ('Dean Trust Ardwick', 'Manchester'),
  ('Dean Trust Rose Bridge', 'Wigan'),
  ('Dean Trust Wigan', 'Wigan'),
  ('Debden Park High School', 'Loughton'),
  ('Debenham High School', 'Stowmarket'),
  ('Dedworth Middle School', 'Windsor'),
  ('Deer Park School', 'Southampton'),
  ('Denbigh High School', 'Luton'),
  ('Denbigh School', 'Milton Keynes'),
  ('Dene Academy', 'Peterlee'),
  ('Dene Magna School', 'Mitcheldean'),
  ('Denefield School', 'Reading'),
  ('Denmark Road High School', 'Gloucester'),
  ('Denton Community Academy', 'Manchester'),
  ('Deptford Green School', 'London'),
  ('Derby Cathedral School', 'Derby'),
  ('Derby Moor Spencer Academy', 'Derby'),
  ('Dereham Neatherd High School', 'Dereham'),
  ('Desborough College', 'Maidenhead'),
  ('Devizes School', 'Devizes'),
  ('Devonport High School for Boys', 'Plymouth'),
  ('Devonport High School for Girls', 'Plymouth'),
  ('Deyes High School', 'Liverpool'),
  ('Didcot Girls'' School', 'Didcot'),
  ('Didsbury High School', 'Manchester'),
  ('Digitech Studio School', 'Bristol'),
  ('Dinnington High School', 'Sheffield'),
  ('Discovery Academy', 'Stoke-on-Trent'),
  ('Diss High School', 'Diss'),
  ('Ditton Park Academy', 'Slough'),
  ('Dixons Allerton Academy', 'Bradford'),
  ('Dixons Broadgreen Academy', 'Liverpool'),
  ('Dixons Brooklands Academy', 'Manchester'),
  ('Dixons City Academy', 'Bradford'),
  ('Dixons Cottingley Academy', 'Bingley'),
  ('Dixons Croxteth Academy', 'Liverpool'),
  ('Dixons Fazakerley Academy', 'Liverpool'),
  ('Dixons Kings Academy', 'Bradford'),
  ('Dixons McMillan Academy', 'Bradford'),
  ('Dixons Newall Green Academy', 'Manchester'),
  ('Dixons Trinity Academy', 'Bradford'),
  ('Dixons Trinity Chapeltown', 'Leeds'),
  ('Dixons Unity Academy', 'Leeds'),
  ('Djanogly City Academy', 'Nottingham'),
  ('Don Valley Academy', 'Doncaster'),
  ('Doncaster UTC', 'Doncaster'),
  ('Dorchester Middle School', 'Dorchester'),
  ('Dormers Wells High School', 'Southall'),
  ('Dorothy Stringer School', 'Brighton'),
  ('Dorset Studio School', 'Dorchester'),
  ('Dover Christ Church Academy', 'Dover'),
  ('Dover Grammar School for Boys', 'Dover'),
  ('Dover Grammar School for Girls', 'Dover'),
  ('Dowdales School', 'Dalton-in-Furness'),
  ('Downend School', 'Bristol'),
  ('Downham Market Academy', 'Downham Market'),
  ('Downlands Community School', 'Hassocks'),
  ('Dr Challoner''s Grammar School', 'Amersham'),
  ('Dr Challoner''s High School', 'Amersham'),
  ('Dr Thomlinson Church of England Middle School', 'Morpeth'),
  ('Drapers'' Academy', 'Romford'),
  ('Drayton Manor High School', 'London'),
  ('Driffield School and Sixth Form', 'Driffield'),
  ('Droitwich Spa High School and Sixth Form Centre', 'Droitwich Spa'),
  ('Dronfield Henry Fanshawe School', 'Dronfield'),
  ('Droylsden Academy', 'Manchester'),
  ('DSLV E-ACT Academy', 'Daventry'),
  ('Duke of York''s Royal Military School', 'Dover'),
  ('Duke''s Aldridge', 'London'),
  ('Dunraven School', 'LONDON'),
  ('Durham Academy', 'Durham'),
  ('Durham Johnston Comprehensive School', 'Durham'),
  ('Durrington High School', 'Worthing'),
  ('Dyke House Sports and Technology College', 'Hartlepool'),
  ('Dyson Perrins CofE Academy', 'Malvern'),
  ('E-Act Bourne End Academy', 'Bourne End'),
  ('E-ACT Crest Academy', 'London'),
  ('E-ACT Heartlands Academy', 'Birmingham'),
  ('E-Act Merchants'' Academy', 'Bristol'),
  ('E-Act Montpelier High School', 'Bristol'),
  ('E-ACT North Birmingham Academy', 'Birmingham'),
  ('E-Act Ousedale School', 'Newport Pagnell'),
  ('E-Act Parkwood Academy', 'Sheffield'),
  ('E-ACT Royton and Crompton Academy', 'Oldham'),
  ('E-ACT Shenley Academy', 'Birmingham'),
  ('E-ACT the Oldham Academy North', 'Oldham'),
  ('Ealing Fields Church of England High School', 'London'),
  ('Earl Mortimer College', 'Leominster'),
  ('Easington Academy', 'Peterlee'),
  ('East Barnet School', 'Barnet'),
  ('East Bergholt High School', 'Colchester'),
  ('East Leake Academy', 'Loughborough'),
  ('East Point Academy', 'Lowestoft'),
  ('Eastbrook School', 'Dagenham'),
  ('Eastbury Community School', 'Barking'),
  ('Eastlea Community School', 'London'),
  ('Eaton Bank Academy', 'Congleton'),
  ('Ecclesfield School', 'Sheffield'),
  ('Eckington School', 'Sheffield'),
  ('EDClass Ltd', 'Rotherham'),
  ('Eden Boys'' Leadership Academy, Birmingham East', 'Birmingham'),
  ('Eden Boys'' Leadership Academy, Bradford', 'Bradford'),
  ('Eden Boys'' Leadership Academy, Manchester', 'Manchester'),
  ('Eden Boys'' School, Birmingham', 'Birmingham'),
  ('Eden Boys'' School, Bolton', 'Bolton'),
  ('Eden Boys'' School, Preston', 'Preston'),
  ('Eden Girls'' Leadership Academy, Birmingham', 'Birmingham'),
  ('Eden Girls'' Leadership Academy, Manchester', 'Manchester'),
  ('Eden Girls'' School, Coventry', 'Coventry'),
  ('Eden Girls'' School, Slough', 'Slough'),
  ('Eden Girls'' School, Waltham Forest', 'London'),
  ('Edgar Wood Academy', 'Heywood'),
  ('Edgbarrow School', 'Crowthorne'),
  ('Edmonton County School', 'London'),
  ('Edward Peake CofE VC School', 'Biggleswade'),
  ('Edwinstree Church of England Middle School', 'Buntingford'),
  ('Eggar''s School', 'Alton'),
  ('Eggbuckland Community College', 'Plymouth'),
  ('Egglescliffe School', 'Stockton-on-Tees'),
  ('EKC Sheppey Secondary', 'Sheerness'),
  ('Elizabeth Garrett Anderson School', 'London'),
  ('Elizabeth Woodville School', 'Roade'),
  ('Ellesmere Park High School', 'Manchester'),
  ('Ellesmere Port Catholic High School, a Voluntary Academy', 'Ellesmere Port'),
  ('Ellesmere Port Church of England College', 'Ellesmere Port'),
  ('Ellis Guilford School', 'Nottingham'),
  ('Ellowes Hall Sports College', 'Dudley'),
  ('Elstree Screen Arts Academy', 'Borehamwood'),
  ('Eltham Hill School', 'London'),
  ('Elthorne Park High School', 'London'),
  ('Ely College', 'Ely'),
  ('Emerson Park Academy', 'Hornchurch'),
  ('Emmanuel Church of England Middle School', 'Verwood'),
  ('Endon High School', 'Stoke-on-Trent'),
  ('Energy Coast UTC', 'Workington'),
  ('Enfield County School for Girls', 'Enfield'),
  ('Enfield Grammar School', 'Enfield'),
  ('Engineering UTC Northern Lincolnshire', 'Scunthorpe'),
  ('English Martyrs Catholic School and Sixth Form College', 'Hartlepool'),
  ('English Martyrs'' Catholic School, A Voluntary Academy', 'Leicester'),
  ('Epping St Johns Church of England School', 'Epping'),
  ('Epsom and Ewell High School', 'Epsom'),
  ('Erasmus Darwin Academy', 'Burntwood'),
  ('Ercall Wood Academy', 'Telford'),
  ('Erdington Academy', 'Birmingham'),
  ('Ermysted''s Grammar School', 'Skipton'),
  ('Ernesford Grange Community Academy', 'Coventry'),
  ('Ernest Bevin Academy', 'London'),
  ('Ernulf Academy', 'St. Neots'),
  ('Esher Church of England High School', 'Esher'),
  ('Essa Academy', 'Bolton'),
  ('Eton Academy', 'Salford'),
  ('Etonbury Academy', 'Arlesey'),
  ('Etone College', 'Nuneaton'),
  ('Europa School UK', 'Abingdon'),
  ('Everest Community Academy', 'Basingstoke'),
  ('Excelsior Academy', 'Newcastle-upon-Tyne'),
  ('Exmouth Community College', 'Exmouth'),
  ('Fairfax', 'Sutton Coldfield'),
  ('Fairfield High School', 'Hereford'),
  ('Fairfield High School', 'Bristol'),
  ('Fairfield High School for Girls', 'Manchester'),
  ('Fairlands Middle School', 'Cheddar'),
  ('Fakenham Academy', 'Fakenham'),
  ('Falinge Park High School', 'Rochdale'),
  ('Falmouth School', 'Falmouth'),
  ('Fareham Academy', 'Fareham'),
  ('Faringdon Community College', 'Faringdon'),
  ('Farlingaye High School', 'Woodbridge'),
  ('Farmor''s School', 'Fairford'),
  ('Farnborough Spencer Academy', 'Nottingham'),
  ('Farnham Heath End', 'Farnham'),
  ('Farringdon Community Academy', 'Sunderland'),
  ('Fearnhill School', 'Letchworth'),
  ('Featherstone High School', 'Southall'),
  ('Felixstowe School', 'Felixstowe'),
  ('Felpham Community College', 'Bognor Regis'),
  ('Ferndown Middle School', 'Ferndown'),
  ('Ferndown Upper School', 'Ferndown'),
  ('Fernwood School', 'Nottingham'),
  ('Ferryhill School', 'Ferryhill'),
  ('Feversham Girls'' Secondary Academy', 'Bradford'),
  ('Filey Academy', 'Filey'),
  ('Finchley Catholic High School', 'London'),
  ('Finham Park 2', 'Coventry'),
  ('Finham Park School', 'Coventry'),
  ('Fir Vale Academy', 'Sheffield'),
  ('Fitzharrys School', 'Abingdon'),
  ('Five Acres High School', 'Coleford'),
  ('Five Rivers Virtual Education', 'Salisbury'),
  ('Fleetwood High School', 'FLEETWOOD'),
  ('Flegg High Ormiston Academy', 'Great Yarmouth'),
  ('Flixton Girls School', 'Manchester'),
  ('Folkestone Academy', 'Folkestone'),
  ('Forest Academy', 'Ilford'),
  ('Forest Gate Community School', 'London'),
  ('Forest Hall School', 'Stansted Mountfitchet'),
  ('Forest Hill School', 'London'),
  ('Forge Valley School & Sixth Form', 'Sheffield'),
  ('Formby High School', 'Liverpool'),
  ('Fort Pitt Grammar School', 'Chatham'),
  ('Fortis Academy', 'Birmingham'),
  ('Fortismere School', 'London'),
  ('Fowey River Academy', 'Fowey'),
  ('Foxford Community School', 'Coventry'),
  ('Framingham Earl High School', 'Norwich'),
  ('Framwellgate School Durham', 'Durham'),
  ('Fred Longworth High School', 'Manchester'),
  ('Frederick Bremer School', 'London'),
  ('Frederick Gent School', 'Alfreton'),
  ('Frederick Gough School', 'Scunthorpe'),
  ('Freebrough Academy', 'Saltburn-By-the-Sea'),
  ('Freman College', 'Buntingford'),
  ('Friern Barnet School', 'London'),
  ('Friesland School', 'Sandiacre'),
  ('Frogmore Community College', 'Yateley'),
  ('Frome Community College', 'Frome'),
  ('Fulbrook School', 'Milton Keynes'),
  ('Fulford School', 'York'),
  ('Fulham Cross Academy', 'London'),
  ('Fulham Cross Girls'' School and Language College', 'London'),
  ('Fullbrook School', 'Addlestone'),
  ('Fullhurst Community College', 'Leicester'),
  ('Fulston Manor School', 'Sittingbourne'),
  ('Fulwood Academy', 'Preston'),
  ('Furness Academy', 'Barrow-in-Furness'),
  ('Furze Platt Senior School', 'Maidenhead'),
  ('Future Academies Watford', 'Watford'),
  ('Futures Institute Banbury', 'Banbury'),
  ('Garforth Academy', 'Leeds'),
  ('Garstang Community Academy', 'Preston'),
  ('Garth Hill College', 'Bracknell'),
  ('Gartree High School', 'Leicester'),
  ('Gateacre School', 'Liverpool'),
  ('Gaynes School', 'Upminster'),
  ('George Abbot School', 'Guildford'),
  ('George Dixon Academy', 'Birmingham'),
  ('George Eliot Academy', 'Nuneaton'),
  ('George Green''s School', 'London'),
  ('George Mitchell School', 'London'),
  ('George Pindar School', 'Scarborough'),
  ('George Salter Academy', 'West Bromwich'),
  ('George Spencer Academy', 'Nottingham'),
  ('George Stephenson High School', 'Newcastle-upon-Tyne'),
  ('Gilbert Inglefield Academy', 'Leighton Buzzard'),
  ('Gildredge House', 'Eastbourne'),
  ('Gillingham School', 'Gillingham'),
  ('Gillotts School', 'Henley-on-Thames'),
  ('Gladesmore Community School', 'London'),
  ('Glebe Farm School', 'Milton Keynes'),
  ('Glebelands School', 'Cranleigh'),
  ('Glendale Middle School', 'Wooler'),
  ('Glenmoor Academy', 'Bournemouth'),
  ('Glenthorne High School', 'Sutton'),
  ('Global Academy', 'Middlesex'),
  ('Glossopdale School and Sixth Form', 'Glossop'),
  ('Gloucester Academy', 'Gloucester'),
  ('Glyn School', 'Epsom'),
  ('Goffs - Churchgate Academy', 'Waltham Cross'),
  ('Goffs Academy', 'Waltham Cross'),
  ('Golborne High School', 'Warrington'),
  ('Goldington Academy', 'Bedford'),
  ('Goodwin Academy', 'Deal'),
  ('Goole Academy', 'Goole'),
  ('Gordano School', 'Bristol'),
  ('Gordon''s School', 'Woking'),
  ('Goresbrook School', 'Dagenham'),
  ('Gosford Hill School', 'Kidlington'),
  ('Gosforth Academy', 'Newcastle-upon-Tyne'),
  ('Gosforth Central Middle School', 'Newcastle-upon-Tyne'),
  ('Gosforth East Middle School', 'Newcastle-upon-Tyne'),
  ('Gosforth Junior High Academy', 'Newcastle-upon-Tyne'),
  ('Gospel Oak School', 'Tipton'),
  ('Grace Academy Coventry', 'Coventry'),
  ('Grace Academy Darlaston', 'Wednesbury'),
  ('Grace Academy Solihull', 'Birmingham'),
  ('Grace College', 'Gateshead'),
  ('Gracewood Academy', 'Potters Bar'),
  ('Graham School', 'Scarborough'),
  ('Granville Academy', 'Swadlincote'),
  ('Graveney School', 'London'),
  ('Gravesend Grammar School', 'Gravesend'),
  ('Grays Convent High School', 'Grays'),
  ('Great Academy Ashton', 'Ashton-under-Lyne'),
  ('Great Baddow High School', 'Chelmsford'),
  ('Great Marlow School', 'Marlow'),
  ('Great Park Academy', 'Newcastle-upon-Tyne'),
  ('Great Sankey High School', 'Warrington')
ON CONFLICT (name, town) DO NOTHING;
